#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLHK")]
	public partial class quanlyhokhauDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCANBO(CANBO instance);
    partial void UpdateCANBO(CANBO instance);
    partial void DeleteCANBO(CANBO instance);
    partial void InsertHOCSINHSINHVIEN(HOCSINHSINHVIEN instance);
    partial void UpdateHOCSINHSINHVIEN(HOCSINHSINHVIEN instance);
    partial void DeleteHOCSINHSINHVIEN(HOCSINHSINHVIEN instance);
    partial void InsertNHANKHAU(NHANKHAU instance);
    partial void UpdateNHANKHAU(NHANKHAU instance);
    partial void DeleteNHANKHAU(NHANKHAU instance);
    partial void InsertNHANKHAUTAMTRU(NHANKHAUTAMTRU instance);
    partial void UpdateNHANKHAUTAMTRU(NHANKHAUTAMTRU instance);
    partial void DeleteNHANKHAUTAMTRU(NHANKHAUTAMTRU instance);
    partial void InsertNHANKHAUTAMVANG(NHANKHAUTAMVANG instance);
    partial void UpdateNHANKHAUTAMVANG(NHANKHAUTAMVANG instance);
    partial void DeleteNHANKHAUTAMVANG(NHANKHAUTAMVANG instance);
    partial void InsertNHANKHAUTHUONGTRU(NHANKHAUTHUONGTRU instance);
    partial void UpdateNHANKHAUTHUONGTRU(NHANKHAUTHUONGTRU instance);
    partial void DeleteNHANKHAUTHUONGTRU(NHANKHAUTHUONGTRU instance);
    partial void InsertSOHOKHAU(SOHOKHAU instance);
    partial void UpdateSOHOKHAU(SOHOKHAU instance);
    partial void DeleteSOHOKHAU(SOHOKHAU instance);
    partial void InsertSOTAMTRU(SOTAMTRU instance);
    partial void UpdateSOTAMTRU(SOTAMTRU instance);
    partial void DeleteSOTAMTRU(SOTAMTRU instance);
    partial void InsertTIENANTIENSU(TIENANTIENSU instance);
    partial void UpdateTIENANTIENSU(TIENANTIENSU instance);
    partial void DeleteTIENANTIENSU(TIENANTIENSU instance);
    partial void InsertTIEUSU(TIEUSU instance);
    partial void UpdateTIEUSU(TIEUSU instance);
    partial void DeleteTIEUSU(TIEUSU instance);
    #endregion
		
		public quanlyhokhauDataContext() : 
				base(global::DTO.Properties.Settings.Default.QLHKConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public quanlyhokhauDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public quanlyhokhauDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public quanlyhokhauDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public quanlyhokhauDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CANBO> CANBOs
		{
			get
			{
				return this.GetTable<CANBO>();
			}
		}
		
		public System.Data.Linq.Table<HOCSINHSINHVIEN> HOCSINHSINHVIENs
		{
			get
			{
				return this.GetTable<HOCSINHSINHVIEN>();
			}
		}
		
		public System.Data.Linq.Table<NHANKHAU> NHANKHAUs
		{
			get
			{
				return this.GetTable<NHANKHAU>();
			}
		}
		
		public System.Data.Linq.Table<NHANKHAUTAMTRU> NHANKHAUTAMTRUs
		{
			get
			{
				return this.GetTable<NHANKHAUTAMTRU>();
			}
		}
		
		public System.Data.Linq.Table<NHANKHAUTAMVANG> NHANKHAUTAMVANGs
		{
			get
			{
				return this.GetTable<NHANKHAUTAMVANG>();
			}
		}
		
		public System.Data.Linq.Table<NHANKHAUTHUONGTRU> NHANKHAUTHUONGTRUs
		{
			get
			{
				return this.GetTable<NHANKHAUTHUONGTRU>();
			}
		}
		
		public System.Data.Linq.Table<SOHOKHAU> SOHOKHAUs
		{
			get
			{
				return this.GetTable<SOHOKHAU>();
			}
		}
		
		public System.Data.Linq.Table<SOTAMTRU> SOTAMTRUs
		{
			get
			{
				return this.GetTable<SOTAMTRU>();
			}
		}
		
		public System.Data.Linq.Table<TIENANTIENSU> TIENANTIENSUs
		{
			get
			{
				return this.GetTable<TIENANTIENSU>();
			}
		}
		
		public System.Data.Linq.Table<TIEUSU> TIEUSUs
		{
			get
			{
				return this.GetTable<TIEUSU>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CANBO")]
	public partial class CANBO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MACANBO;
		
		private string _MANHANKHAUTHUONGTRU;
		
		private string _TENTAIKHOAN;
		
		private string _MATKHAU;
		
		private string _LOAICANBO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMACANBOChanging(string value);
    partial void OnMACANBOChanged();
    partial void OnMANHANKHAUTHUONGTRUChanging(string value);
    partial void OnMANHANKHAUTHUONGTRUChanged();
    partial void OnTENTAIKHOANChanging(string value);
    partial void OnTENTAIKHOANChanged();
    partial void OnMATKHAUChanging(string value);
    partial void OnMATKHAUChanged();
    partial void OnLOAICANBOChanging(string value);
    partial void OnLOAICANBOChanged();
    #endregion
		
		public CANBO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACANBO", DbType="Char(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MACANBO
		{
			get
			{
				return this._MACANBO;
			}
			set
			{
				if ((this._MACANBO != value))
				{
					this.OnMACANBOChanging(value);
					this.SendPropertyChanging();
					this._MACANBO = value;
					this.SendPropertyChanged("MACANBO");
					this.OnMACANBOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANHANKHAUTHUONGTRU", DbType="Char(9) NOT NULL", CanBeNull=false)]
		public string MANHANKHAUTHUONGTRU
		{
			get
			{
				return this._MANHANKHAUTHUONGTRU;
			}
			set
			{
				if ((this._MANHANKHAUTHUONGTRU != value))
				{
					this.OnMANHANKHAUTHUONGTRUChanging(value);
					this.SendPropertyChanging();
					this._MANHANKHAUTHUONGTRU = value;
					this.SendPropertyChanged("MANHANKHAUTHUONGTRU");
					this.OnMANHANKHAUTHUONGTRUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTAIKHOAN", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string TENTAIKHOAN
		{
			get
			{
				return this._TENTAIKHOAN;
			}
			set
			{
				if ((this._TENTAIKHOAN != value))
				{
					this.OnTENTAIKHOANChanging(value);
					this.SendPropertyChanging();
					this._TENTAIKHOAN = value;
					this.SendPropertyChanged("TENTAIKHOAN");
					this.OnTENTAIKHOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATKHAU", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string MATKHAU
		{
			get
			{
				return this._MATKHAU;
			}
			set
			{
				if ((this._MATKHAU != value))
				{
					this.OnMATKHAUChanging(value);
					this.SendPropertyChanging();
					this._MATKHAU = value;
					this.SendPropertyChanged("MATKHAU");
					this.OnMATKHAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAICANBO", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string LOAICANBO
		{
			get
			{
				return this._LOAICANBO;
			}
			set
			{
				if ((this._LOAICANBO != value))
				{
					this.OnLOAICANBOChanging(value);
					this.SendPropertyChanging();
					this._LOAICANBO = value;
					this.SendPropertyChanged("LOAICANBO");
					this.OnLOAICANBOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOCSINHSINHVIEN")]
	public partial class HOCSINHSINHVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAHSSV;
		
		private string _MADINHDANH;
		
		private string _TRUONG;
		
		private string _DIACHITHUONGTRU;
		
		private System.DateTime _THOIGIANBATDAUTAMTRUTHUONGTRU;
		
		private System.DateTime _THOIGIANKETTHUCTAMTRUTHUONGTRU;
		
		private string _VIPHAM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAHSSVChanging(string value);
    partial void OnMAHSSVChanged();
    partial void OnMADINHDANHChanging(string value);
    partial void OnMADINHDANHChanged();
    partial void OnTRUONGChanging(string value);
    partial void OnTRUONGChanged();
    partial void OnDIACHITHUONGTRUChanging(string value);
    partial void OnDIACHITHUONGTRUChanged();
    partial void OnTHOIGIANBATDAUTAMTRUTHUONGTRUChanging(System.DateTime value);
    partial void OnTHOIGIANBATDAUTAMTRUTHUONGTRUChanged();
    partial void OnTHOIGIANKETTHUCTAMTRUTHUONGTRUChanging(System.DateTime value);
    partial void OnTHOIGIANKETTHUCTAMTRUTHUONGTRUChanged();
    partial void OnVIPHAMChanging(string value);
    partial void OnVIPHAMChanged();
    #endregion
		
		public HOCSINHSINHVIEN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHSSV", DbType="Char(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAHSSV
		{
			get
			{
				return this._MAHSSV;
			}
			set
			{
				if ((this._MAHSSV != value))
				{
					this.OnMAHSSVChanging(value);
					this.SendPropertyChanging();
					this._MAHSSV = value;
					this.SendPropertyChanged("MAHSSV");
					this.OnMAHSSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADINHDANH", DbType="Char(12) NOT NULL", CanBeNull=false)]
		public string MADINHDANH
		{
			get
			{
				return this._MADINHDANH;
			}
			set
			{
				if ((this._MADINHDANH != value))
				{
					this.OnMADINHDANHChanging(value);
					this.SendPropertyChanging();
					this._MADINHDANH = value;
					this.SendPropertyChanged("MADINHDANH");
					this.OnMADINHDANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRUONG", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string TRUONG
		{
			get
			{
				return this._TRUONG;
			}
			set
			{
				if ((this._TRUONG != value))
				{
					this.OnTRUONGChanging(value);
					this.SendPropertyChanging();
					this._TRUONG = value;
					this.SendPropertyChanged("TRUONG");
					this.OnTRUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHITHUONGTRU", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string DIACHITHUONGTRU
		{
			get
			{
				return this._DIACHITHUONGTRU;
			}
			set
			{
				if ((this._DIACHITHUONGTRU != value))
				{
					this.OnDIACHITHUONGTRUChanging(value);
					this.SendPropertyChanging();
					this._DIACHITHUONGTRU = value;
					this.SendPropertyChanged("DIACHITHUONGTRU");
					this.OnDIACHITHUONGTRUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THOIGIANBATDAUTAMTRUTHUONGTRU", DbType="Date NOT NULL")]
		public System.DateTime THOIGIANBATDAUTAMTRUTHUONGTRU
		{
			get
			{
				return this._THOIGIANBATDAUTAMTRUTHUONGTRU;
			}
			set
			{
				if ((this._THOIGIANBATDAUTAMTRUTHUONGTRU != value))
				{
					this.OnTHOIGIANBATDAUTAMTRUTHUONGTRUChanging(value);
					this.SendPropertyChanging();
					this._THOIGIANBATDAUTAMTRUTHUONGTRU = value;
					this.SendPropertyChanged("THOIGIANBATDAUTAMTRUTHUONGTRU");
					this.OnTHOIGIANBATDAUTAMTRUTHUONGTRUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THOIGIANKETTHUCTAMTRUTHUONGTRU", DbType="Date NOT NULL")]
		public System.DateTime THOIGIANKETTHUCTAMTRUTHUONGTRU
		{
			get
			{
				return this._THOIGIANKETTHUCTAMTRUTHUONGTRU;
			}
			set
			{
				if ((this._THOIGIANKETTHUCTAMTRUTHUONGTRU != value))
				{
					this.OnTHOIGIANKETTHUCTAMTRUTHUONGTRUChanging(value);
					this.SendPropertyChanging();
					this._THOIGIANKETTHUCTAMTRUTHUONGTRU = value;
					this.SendPropertyChanged("THOIGIANKETTHUCTAMTRUTHUONGTRU");
					this.OnTHOIGIANKETTHUCTAMTRUTHUONGTRUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VIPHAM", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string VIPHAM
		{
			get
			{
				return this._VIPHAM;
			}
			set
			{
				if ((this._VIPHAM != value))
				{
					this.OnVIPHAMChanging(value);
					this.SendPropertyChanging();
					this._VIPHAM = value;
					this.SendPropertyChanged("VIPHAM");
					this.OnVIPHAMChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANKHAU")]
	public partial class NHANKHAU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MADINHDANH;
		
		private string _HOTEN;
		
		private string _TENKHAC;
		
		private System.DateTime _NGAYSINH;
		
		private string _GIOITINH;
		
		private string _NOISINH;
		
		private string _NGUYENQUAN;
		
		private string _DANTOC;
		
		private string _TONGIAO;
		
		private string _QUOCTICH;
		
		private string _HOCHIEU;
		
		private string _NOITHUONGTRU;
		
		private string _DIACHIHIENNAY;
		
		private string _SDT;
		
		private string _TRINHDOHOCVAN;
		
		private string _TRINHDOCHUYENMON;
		
		private string _BIETTIENGDANTOC;
		
		private string _TRINHDONGOAINGU;
		
		private string _NGHENGHIEP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMADINHDANHChanging(string value);
    partial void OnMADINHDANHChanged();
    partial void OnHOTENChanging(string value);
    partial void OnHOTENChanged();
    partial void OnTENKHACChanging(string value);
    partial void OnTENKHACChanged();
    partial void OnNGAYSINHChanging(System.DateTime value);
    partial void OnNGAYSINHChanged();
    partial void OnGIOITINHChanging(string value);
    partial void OnGIOITINHChanged();
    partial void OnNOISINHChanging(string value);
    partial void OnNOISINHChanged();
    partial void OnNGUYENQUANChanging(string value);
    partial void OnNGUYENQUANChanged();
    partial void OnDANTOCChanging(string value);
    partial void OnDANTOCChanged();
    partial void OnTONGIAOChanging(string value);
    partial void OnTONGIAOChanged();
    partial void OnQUOCTICHChanging(string value);
    partial void OnQUOCTICHChanged();
    partial void OnHOCHIEUChanging(string value);
    partial void OnHOCHIEUChanged();
    partial void OnNOITHUONGTRUChanging(string value);
    partial void OnNOITHUONGTRUChanged();
    partial void OnDIACHIHIENNAYChanging(string value);
    partial void OnDIACHIHIENNAYChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnTRINHDOHOCVANChanging(string value);
    partial void OnTRINHDOHOCVANChanged();
    partial void OnTRINHDOCHUYENMONChanging(string value);
    partial void OnTRINHDOCHUYENMONChanged();
    partial void OnBIETTIENGDANTOCChanging(string value);
    partial void OnBIETTIENGDANTOCChanged();
    partial void OnTRINHDONGOAINGUChanging(string value);
    partial void OnTRINHDONGOAINGUChanged();
    partial void OnNGHENGHIEPChanging(string value);
    partial void OnNGHENGHIEPChanged();
    #endregion
		
		public NHANKHAU()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADINHDANH", DbType="Char(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MADINHDANH
		{
			get
			{
				return this._MADINHDANH;
			}
			set
			{
				if ((this._MADINHDANH != value))
				{
					this.OnMADINHDANHChanging(value);
					this.SendPropertyChanging();
					this._MADINHDANH = value;
					this.SendPropertyChanged("MADINHDANH");
					this.OnMADINHDANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string HOTEN
		{
			get
			{
				return this._HOTEN;
			}
			set
			{
				if ((this._HOTEN != value))
				{
					this.OnHOTENChanging(value);
					this.SendPropertyChanging();
					this._HOTEN = value;
					this.SendPropertyChanged("HOTEN");
					this.OnHOTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENKHAC", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string TENKHAC
		{
			get
			{
				return this._TENKHAC;
			}
			set
			{
				if ((this._TENKHAC != value))
				{
					this.OnTENKHACChanging(value);
					this.SendPropertyChanging();
					this._TENKHAC = value;
					this.SendPropertyChanged("TENKHAC");
					this.OnTENKHACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="Date NOT NULL")]
		public System.DateTime NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOISINH", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string NOISINH
		{
			get
			{
				return this._NOISINH;
			}
			set
			{
				if ((this._NOISINH != value))
				{
					this.OnNOISINHChanging(value);
					this.SendPropertyChanging();
					this._NOISINH = value;
					this.SendPropertyChanged("NOISINH");
					this.OnNOISINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGUYENQUAN", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string NGUYENQUAN
		{
			get
			{
				return this._NGUYENQUAN;
			}
			set
			{
				if ((this._NGUYENQUAN != value))
				{
					this.OnNGUYENQUANChanging(value);
					this.SendPropertyChanging();
					this._NGUYENQUAN = value;
					this.SendPropertyChanged("NGUYENQUAN");
					this.OnNGUYENQUANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DANTOC", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string DANTOC
		{
			get
			{
				return this._DANTOC;
			}
			set
			{
				if ((this._DANTOC != value))
				{
					this.OnDANTOCChanging(value);
					this.SendPropertyChanging();
					this._DANTOC = value;
					this.SendPropertyChanged("DANTOC");
					this.OnDANTOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGIAO", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string TONGIAO
		{
			get
			{
				return this._TONGIAO;
			}
			set
			{
				if ((this._TONGIAO != value))
				{
					this.OnTONGIAOChanging(value);
					this.SendPropertyChanging();
					this._TONGIAO = value;
					this.SendPropertyChanged("TONGIAO");
					this.OnTONGIAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUOCTICH", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string QUOCTICH
		{
			get
			{
				return this._QUOCTICH;
			}
			set
			{
				if ((this._QUOCTICH != value))
				{
					this.OnQUOCTICHChanging(value);
					this.SendPropertyChanging();
					this._QUOCTICH = value;
					this.SendPropertyChanged("QUOCTICH");
					this.OnQUOCTICHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOCHIEU", DbType="VarChar(20)")]
		public string HOCHIEU
		{
			get
			{
				return this._HOCHIEU;
			}
			set
			{
				if ((this._HOCHIEU != value))
				{
					this.OnHOCHIEUChanging(value);
					this.SendPropertyChanging();
					this._HOCHIEU = value;
					this.SendPropertyChanged("HOCHIEU");
					this.OnHOCHIEUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOITHUONGTRU", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string NOITHUONGTRU
		{
			get
			{
				return this._NOITHUONGTRU;
			}
			set
			{
				if ((this._NOITHUONGTRU != value))
				{
					this.OnNOITHUONGTRUChanging(value);
					this.SendPropertyChanging();
					this._NOITHUONGTRU = value;
					this.SendPropertyChanged("NOITHUONGTRU");
					this.OnNOITHUONGTRUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHIHIENNAY", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string DIACHIHIENNAY
		{
			get
			{
				return this._DIACHIHIENNAY;
			}
			set
			{
				if ((this._DIACHIHIENNAY != value))
				{
					this.OnDIACHIHIENNAYChanging(value);
					this.SendPropertyChanging();
					this._DIACHIHIENNAY = value;
					this.SendPropertyChanged("DIACHIHIENNAY");
					this.OnDIACHIHIENNAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Char(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRINHDOHOCVAN", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string TRINHDOHOCVAN
		{
			get
			{
				return this._TRINHDOHOCVAN;
			}
			set
			{
				if ((this._TRINHDOHOCVAN != value))
				{
					this.OnTRINHDOHOCVANChanging(value);
					this.SendPropertyChanging();
					this._TRINHDOHOCVAN = value;
					this.SendPropertyChanged("TRINHDOHOCVAN");
					this.OnTRINHDOHOCVANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRINHDOCHUYENMON", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string TRINHDOCHUYENMON
		{
			get
			{
				return this._TRINHDOCHUYENMON;
			}
			set
			{
				if ((this._TRINHDOCHUYENMON != value))
				{
					this.OnTRINHDOCHUYENMONChanging(value);
					this.SendPropertyChanging();
					this._TRINHDOCHUYENMON = value;
					this.SendPropertyChanged("TRINHDOCHUYENMON");
					this.OnTRINHDOCHUYENMONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIETTIENGDANTOC", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string BIETTIENGDANTOC
		{
			get
			{
				return this._BIETTIENGDANTOC;
			}
			set
			{
				if ((this._BIETTIENGDANTOC != value))
				{
					this.OnBIETTIENGDANTOCChanging(value);
					this.SendPropertyChanging();
					this._BIETTIENGDANTOC = value;
					this.SendPropertyChanged("BIETTIENGDANTOC");
					this.OnBIETTIENGDANTOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRINHDONGOAINGU", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string TRINHDONGOAINGU
		{
			get
			{
				return this._TRINHDONGOAINGU;
			}
			set
			{
				if ((this._TRINHDONGOAINGU != value))
				{
					this.OnTRINHDONGOAINGUChanging(value);
					this.SendPropertyChanging();
					this._TRINHDONGOAINGU = value;
					this.SendPropertyChanged("TRINHDONGOAINGU");
					this.OnTRINHDONGOAINGUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGHENGHIEP", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string NGHENGHIEP
		{
			get
			{
				return this._NGHENGHIEP;
			}
			set
			{
				if ((this._NGHENGHIEP != value))
				{
					this.OnNGHENGHIEPChanging(value);
					this.SendPropertyChanging();
					this._NGHENGHIEP = value;
					this.SendPropertyChanged("NGHENGHIEP");
					this.OnNGHENGHIEPChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANKHAUTAMTRU")]
	public partial class NHANKHAUTAMTRU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANHAKHAUTAMTRU;
		
		private string _MADINHDANH;
		
		private string _NOITAMTRU;
		
		private System.DateTime _TUNGAY;
		
		private System.DateTime _DENNGAY;
		
		private string _LYDO;
		
		private string _SOSOTAMTRU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANHAKHAUTAMTRUChanging(string value);
    partial void OnMANHAKHAUTAMTRUChanged();
    partial void OnMADINHDANHChanging(string value);
    partial void OnMADINHDANHChanged();
    partial void OnNOITAMTRUChanging(string value);
    partial void OnNOITAMTRUChanged();
    partial void OnTUNGAYChanging(System.DateTime value);
    partial void OnTUNGAYChanged();
    partial void OnDENNGAYChanging(System.DateTime value);
    partial void OnDENNGAYChanged();
    partial void OnLYDOChanging(string value);
    partial void OnLYDOChanged();
    partial void OnSOSOTAMTRUChanging(string value);
    partial void OnSOSOTAMTRUChanged();
    #endregion
		
		public NHANKHAUTAMTRU()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANHAKHAUTAMTRU", DbType="Char(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANHAKHAUTAMTRU
		{
			get
			{
				return this._MANHAKHAUTAMTRU;
			}
			set
			{
				if ((this._MANHAKHAUTAMTRU != value))
				{
					this.OnMANHAKHAUTAMTRUChanging(value);
					this.SendPropertyChanging();
					this._MANHAKHAUTAMTRU = value;
					this.SendPropertyChanged("MANHAKHAUTAMTRU");
					this.OnMANHAKHAUTAMTRUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADINHDANH", DbType="Char(12) NOT NULL", CanBeNull=false)]
		public string MADINHDANH
		{
			get
			{
				return this._MADINHDANH;
			}
			set
			{
				if ((this._MADINHDANH != value))
				{
					this.OnMADINHDANHChanging(value);
					this.SendPropertyChanging();
					this._MADINHDANH = value;
					this.SendPropertyChanged("MADINHDANH");
					this.OnMADINHDANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOITAMTRU", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string NOITAMTRU
		{
			get
			{
				return this._NOITAMTRU;
			}
			set
			{
				if ((this._NOITAMTRU != value))
				{
					this.OnNOITAMTRUChanging(value);
					this.SendPropertyChanging();
					this._NOITAMTRU = value;
					this.SendPropertyChanged("NOITAMTRU");
					this.OnNOITAMTRUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TUNGAY", DbType="Date NOT NULL")]
		public System.DateTime TUNGAY
		{
			get
			{
				return this._TUNGAY;
			}
			set
			{
				if ((this._TUNGAY != value))
				{
					this.OnTUNGAYChanging(value);
					this.SendPropertyChanging();
					this._TUNGAY = value;
					this.SendPropertyChanged("TUNGAY");
					this.OnTUNGAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DENNGAY", DbType="Date NOT NULL")]
		public System.DateTime DENNGAY
		{
			get
			{
				return this._DENNGAY;
			}
			set
			{
				if ((this._DENNGAY != value))
				{
					this.OnDENNGAYChanging(value);
					this.SendPropertyChanging();
					this._DENNGAY = value;
					this.SendPropertyChanged("DENNGAY");
					this.OnDENNGAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LYDO", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string LYDO
		{
			get
			{
				return this._LYDO;
			}
			set
			{
				if ((this._LYDO != value))
				{
					this.OnLYDOChanging(value);
					this.SendPropertyChanging();
					this._LYDO = value;
					this.SendPropertyChanged("LYDO");
					this.OnLYDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOSOTAMTRU", DbType="Char(9) NOT NULL", CanBeNull=false)]
		public string SOSOTAMTRU
		{
			get
			{
				return this._SOSOTAMTRU;
			}
			set
			{
				if ((this._SOSOTAMTRU != value))
				{
					this.OnSOSOTAMTRUChanging(value);
					this.SendPropertyChanging();
					this._SOSOTAMTRU = value;
					this.SendPropertyChanged("SOSOTAMTRU");
					this.OnSOSOTAMTRUChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANKHAUTAMVANG")]
	public partial class NHANKHAUTAMVANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANHANKHAUTAMVANG;
		
		private string _MADINHDANH;
		
		private System.DateTime _NGAYBATDAUTAMVANG;
		
		private System.DateTime _NGAYKETTHUCTAMVANG;
		
		private string _LYDO;
		
		private string _NOIDEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANHANKHAUTAMVANGChanging(string value);
    partial void OnMANHANKHAUTAMVANGChanged();
    partial void OnMADINHDANHChanging(string value);
    partial void OnMADINHDANHChanged();
    partial void OnNGAYBATDAUTAMVANGChanging(System.DateTime value);
    partial void OnNGAYBATDAUTAMVANGChanged();
    partial void OnNGAYKETTHUCTAMVANGChanging(System.DateTime value);
    partial void OnNGAYKETTHUCTAMVANGChanged();
    partial void OnLYDOChanging(string value);
    partial void OnLYDOChanged();
    partial void OnNOIDENChanging(string value);
    partial void OnNOIDENChanged();
    #endregion
		
		public NHANKHAUTAMVANG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANHANKHAUTAMVANG", DbType="Char(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANHANKHAUTAMVANG
		{
			get
			{
				return this._MANHANKHAUTAMVANG;
			}
			set
			{
				if ((this._MANHANKHAUTAMVANG != value))
				{
					this.OnMANHANKHAUTAMVANGChanging(value);
					this.SendPropertyChanging();
					this._MANHANKHAUTAMVANG = value;
					this.SendPropertyChanged("MANHANKHAUTAMVANG");
					this.OnMANHANKHAUTAMVANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADINHDANH", DbType="Char(12) NOT NULL", CanBeNull=false)]
		public string MADINHDANH
		{
			get
			{
				return this._MADINHDANH;
			}
			set
			{
				if ((this._MADINHDANH != value))
				{
					this.OnMADINHDANHChanging(value);
					this.SendPropertyChanging();
					this._MADINHDANH = value;
					this.SendPropertyChanged("MADINHDANH");
					this.OnMADINHDANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYBATDAUTAMVANG", DbType="Date NOT NULL")]
		public System.DateTime NGAYBATDAUTAMVANG
		{
			get
			{
				return this._NGAYBATDAUTAMVANG;
			}
			set
			{
				if ((this._NGAYBATDAUTAMVANG != value))
				{
					this.OnNGAYBATDAUTAMVANGChanging(value);
					this.SendPropertyChanging();
					this._NGAYBATDAUTAMVANG = value;
					this.SendPropertyChanged("NGAYBATDAUTAMVANG");
					this.OnNGAYBATDAUTAMVANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYKETTHUCTAMVANG", DbType="Date NOT NULL")]
		public System.DateTime NGAYKETTHUCTAMVANG
		{
			get
			{
				return this._NGAYKETTHUCTAMVANG;
			}
			set
			{
				if ((this._NGAYKETTHUCTAMVANG != value))
				{
					this.OnNGAYKETTHUCTAMVANGChanging(value);
					this.SendPropertyChanging();
					this._NGAYKETTHUCTAMVANG = value;
					this.SendPropertyChanged("NGAYKETTHUCTAMVANG");
					this.OnNGAYKETTHUCTAMVANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LYDO", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string LYDO
		{
			get
			{
				return this._LYDO;
			}
			set
			{
				if ((this._LYDO != value))
				{
					this.OnLYDOChanging(value);
					this.SendPropertyChanging();
					this._LYDO = value;
					this.SendPropertyChanged("LYDO");
					this.OnLYDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOIDEN", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string NOIDEN
		{
			get
			{
				return this._NOIDEN;
			}
			set
			{
				if ((this._NOIDEN != value))
				{
					this.OnNOIDENChanging(value);
					this.SendPropertyChanging();
					this._NOIDEN = value;
					this.SendPropertyChanged("NOIDEN");
					this.OnNOIDENChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANKHAUTHUONGTRU")]
	public partial class NHANKHAUTHUONGTRU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANHANKHAUTHUONGTRU;
		
		private string _MADINHDANH;
		
		private string _DIACHITHUONGTRU;
		
		private string _QUANHEVOICHUHO;
		
		private string _SOSOHOKHAU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANHANKHAUTHUONGTRUChanging(string value);
    partial void OnMANHANKHAUTHUONGTRUChanged();
    partial void OnMADINHDANHChanging(string value);
    partial void OnMADINHDANHChanged();
    partial void OnDIACHITHUONGTRUChanging(string value);
    partial void OnDIACHITHUONGTRUChanged();
    partial void OnQUANHEVOICHUHOChanging(string value);
    partial void OnQUANHEVOICHUHOChanged();
    partial void OnSOSOHOKHAUChanging(string value);
    partial void OnSOSOHOKHAUChanged();
    #endregion
		
		public NHANKHAUTHUONGTRU()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANHANKHAUTHUONGTRU", DbType="Char(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANHANKHAUTHUONGTRU
		{
			get
			{
				return this._MANHANKHAUTHUONGTRU;
			}
			set
			{
				if ((this._MANHANKHAUTHUONGTRU != value))
				{
					this.OnMANHANKHAUTHUONGTRUChanging(value);
					this.SendPropertyChanging();
					this._MANHANKHAUTHUONGTRU = value;
					this.SendPropertyChanged("MANHANKHAUTHUONGTRU");
					this.OnMANHANKHAUTHUONGTRUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADINHDANH", DbType="Char(12) NOT NULL", CanBeNull=false)]
		public string MADINHDANH
		{
			get
			{
				return this._MADINHDANH;
			}
			set
			{
				if ((this._MADINHDANH != value))
				{
					this.OnMADINHDANHChanging(value);
					this.SendPropertyChanging();
					this._MADINHDANH = value;
					this.SendPropertyChanged("MADINHDANH");
					this.OnMADINHDANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHITHUONGTRU", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string DIACHITHUONGTRU
		{
			get
			{
				return this._DIACHITHUONGTRU;
			}
			set
			{
				if ((this._DIACHITHUONGTRU != value))
				{
					this.OnDIACHITHUONGTRUChanging(value);
					this.SendPropertyChanging();
					this._DIACHITHUONGTRU = value;
					this.SendPropertyChanged("DIACHITHUONGTRU");
					this.OnDIACHITHUONGTRUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANHEVOICHUHO", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string QUANHEVOICHUHO
		{
			get
			{
				return this._QUANHEVOICHUHO;
			}
			set
			{
				if ((this._QUANHEVOICHUHO != value))
				{
					this.OnQUANHEVOICHUHOChanging(value);
					this.SendPropertyChanging();
					this._QUANHEVOICHUHO = value;
					this.SendPropertyChanged("QUANHEVOICHUHO");
					this.OnQUANHEVOICHUHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOSOHOKHAU", DbType="Char(9) NOT NULL", CanBeNull=false)]
		public string SOSOHOKHAU
		{
			get
			{
				return this._SOSOHOKHAU;
			}
			set
			{
				if ((this._SOSOHOKHAU != value))
				{
					this.OnSOSOHOKHAUChanging(value);
					this.SendPropertyChanging();
					this._SOSOHOKHAU = value;
					this.SendPropertyChanged("SOSOHOKHAU");
					this.OnSOSOHOKHAUChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SOHOKHAU")]
	public partial class SOHOKHAU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SOSOHOKHAU;
		
		private string _MACHUHO;
		
		private string _DIACHI;
		
		private System.DateTime _NGAYCAP;
		
		private string _SODANGKY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSOSOHOKHAUChanging(string value);
    partial void OnSOSOHOKHAUChanged();
    partial void OnMACHUHOChanging(string value);
    partial void OnMACHUHOChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnNGAYCAPChanging(System.DateTime value);
    partial void OnNGAYCAPChanged();
    partial void OnSODANGKYChanging(string value);
    partial void OnSODANGKYChanged();
    #endregion
		
		public SOHOKHAU()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOSOHOKHAU", DbType="Char(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SOSOHOKHAU
		{
			get
			{
				return this._SOSOHOKHAU;
			}
			set
			{
				if ((this._SOSOHOKHAU != value))
				{
					this.OnSOSOHOKHAUChanging(value);
					this.SendPropertyChanging();
					this._SOSOHOKHAU = value;
					this.SendPropertyChanged("SOSOHOKHAU");
					this.OnSOSOHOKHAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACHUHO", DbType="Char(9) NOT NULL", CanBeNull=false)]
		public string MACHUHO
		{
			get
			{
				return this._MACHUHO;
			}
			set
			{
				if ((this._MACHUHO != value))
				{
					this.OnMACHUHOChanging(value);
					this.SendPropertyChanging();
					this._MACHUHO = value;
					this.SendPropertyChanged("MACHUHO");
					this.OnMACHUHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYCAP", DbType="Date NOT NULL")]
		public System.DateTime NGAYCAP
		{
			get
			{
				return this._NGAYCAP;
			}
			set
			{
				if ((this._NGAYCAP != value))
				{
					this.OnNGAYCAPChanging(value);
					this.SendPropertyChanging();
					this._NGAYCAP = value;
					this.SendPropertyChanged("NGAYCAP");
					this.OnNGAYCAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SODANGKY", DbType="Char(7) NOT NULL", CanBeNull=false)]
		public string SODANGKY
		{
			get
			{
				return this._SODANGKY;
			}
			set
			{
				if ((this._SODANGKY != value))
				{
					this.OnSODANGKYChanging(value);
					this.SendPropertyChanging();
					this._SODANGKY = value;
					this.SendPropertyChanged("SODANGKY");
					this.OnSODANGKYChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SOTAMTRU")]
	public partial class SOTAMTRU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SOSOTAMTRU;
		
		private string _CHUHO;
		
		private string _NOITAMTRU;
		
		private System.DateTime _NGAYCAP;
		
		private System.DateTime _DENNGAY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSOSOTAMTRUChanging(string value);
    partial void OnSOSOTAMTRUChanged();
    partial void OnCHUHOChanging(string value);
    partial void OnCHUHOChanged();
    partial void OnNOITAMTRUChanging(string value);
    partial void OnNOITAMTRUChanged();
    partial void OnNGAYCAPChanging(System.DateTime value);
    partial void OnNGAYCAPChanged();
    partial void OnDENNGAYChanging(System.DateTime value);
    partial void OnDENNGAYChanged();
    #endregion
		
		public SOTAMTRU()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOSOTAMTRU", DbType="Char(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SOSOTAMTRU
		{
			get
			{
				return this._SOSOTAMTRU;
			}
			set
			{
				if ((this._SOSOTAMTRU != value))
				{
					this.OnSOSOTAMTRUChanging(value);
					this.SendPropertyChanging();
					this._SOSOTAMTRU = value;
					this.SendPropertyChanged("SOSOTAMTRU");
					this.OnSOSOTAMTRUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHUHO", DbType="Char(9) NOT NULL", CanBeNull=false)]
		public string CHUHO
		{
			get
			{
				return this._CHUHO;
			}
			set
			{
				if ((this._CHUHO != value))
				{
					this.OnCHUHOChanging(value);
					this.SendPropertyChanging();
					this._CHUHO = value;
					this.SendPropertyChanged("CHUHO");
					this.OnCHUHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOITAMTRU", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string NOITAMTRU
		{
			get
			{
				return this._NOITAMTRU;
			}
			set
			{
				if ((this._NOITAMTRU != value))
				{
					this.OnNOITAMTRUChanging(value);
					this.SendPropertyChanging();
					this._NOITAMTRU = value;
					this.SendPropertyChanged("NOITAMTRU");
					this.OnNOITAMTRUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYCAP", DbType="Date NOT NULL")]
		public System.DateTime NGAYCAP
		{
			get
			{
				return this._NGAYCAP;
			}
			set
			{
				if ((this._NGAYCAP != value))
				{
					this.OnNGAYCAPChanging(value);
					this.SendPropertyChanging();
					this._NGAYCAP = value;
					this.SendPropertyChanged("NGAYCAP");
					this.OnNGAYCAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DENNGAY", DbType="Date NOT NULL")]
		public System.DateTime DENNGAY
		{
			get
			{
				return this._DENNGAY;
			}
			set
			{
				if ((this._DENNGAY != value))
				{
					this.OnDENNGAYChanging(value);
					this.SendPropertyChanging();
					this._DENNGAY = value;
					this.SendPropertyChanged("DENNGAY");
					this.OnDENNGAYChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TIENANTIENSU")]
	public partial class TIENANTIENSU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATIENANTIENSU;
		
		private string _MADINHDANH;
		
		private string _TOIDANH;
		
		private string _HINHPHAT;
		
		private string _BANAN;
		
		private System.DateTime _NGAYPHAT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATIENANTIENSUChanging(string value);
    partial void OnMATIENANTIENSUChanged();
    partial void OnMADINHDANHChanging(string value);
    partial void OnMADINHDANHChanged();
    partial void OnTOIDANHChanging(string value);
    partial void OnTOIDANHChanged();
    partial void OnHINHPHATChanging(string value);
    partial void OnHINHPHATChanged();
    partial void OnBANANChanging(string value);
    partial void OnBANANChanged();
    partial void OnNGAYPHATChanging(System.DateTime value);
    partial void OnNGAYPHATChanged();
    #endregion
		
		public TIENANTIENSU()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATIENANTIENSU", DbType="Char(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATIENANTIENSU
		{
			get
			{
				return this._MATIENANTIENSU;
			}
			set
			{
				if ((this._MATIENANTIENSU != value))
				{
					this.OnMATIENANTIENSUChanging(value);
					this.SendPropertyChanging();
					this._MATIENANTIENSU = value;
					this.SendPropertyChanged("MATIENANTIENSU");
					this.OnMATIENANTIENSUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADINHDANH", DbType="Char(12) NOT NULL", CanBeNull=false)]
		public string MADINHDANH
		{
			get
			{
				return this._MADINHDANH;
			}
			set
			{
				if ((this._MADINHDANH != value))
				{
					this.OnMADINHDANHChanging(value);
					this.SendPropertyChanging();
					this._MADINHDANH = value;
					this.SendPropertyChanged("MADINHDANH");
					this.OnMADINHDANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOIDANH", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string TOIDANH
		{
			get
			{
				return this._TOIDANH;
			}
			set
			{
				if ((this._TOIDANH != value))
				{
					this.OnTOIDANHChanging(value);
					this.SendPropertyChanging();
					this._TOIDANH = value;
					this.SendPropertyChanged("TOIDANH");
					this.OnTOIDANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHPHAT", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string HINHPHAT
		{
			get
			{
				return this._HINHPHAT;
			}
			set
			{
				if ((this._HINHPHAT != value))
				{
					this.OnHINHPHATChanging(value);
					this.SendPropertyChanging();
					this._HINHPHAT = value;
					this.SendPropertyChanged("HINHPHAT");
					this.OnHINHPHATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BANAN", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string BANAN
		{
			get
			{
				return this._BANAN;
			}
			set
			{
				if ((this._BANAN != value))
				{
					this.OnBANANChanging(value);
					this.SendPropertyChanging();
					this._BANAN = value;
					this.SendPropertyChanged("BANAN");
					this.OnBANANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYPHAT", DbType="Date NOT NULL")]
		public System.DateTime NGAYPHAT
		{
			get
			{
				return this._NGAYPHAT;
			}
			set
			{
				if ((this._NGAYPHAT != value))
				{
					this.OnNGAYPHATChanging(value);
					this.SendPropertyChanging();
					this._NGAYPHAT = value;
					this.SendPropertyChanged("NGAYPHAT");
					this.OnNGAYPHATChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TIEUSU")]
	public partial class TIEUSU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATIEUSU;
		
		private string _MADINHDANH;
		
		private System.DateTime _THOIGIANBATDAU;
		
		private System.DateTime _THOIGIANKETTHUC;
		
		private string _CHOO;
		
		private string _NGHENGHIEP;
		
		private string _NOILAMVIEC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATIEUSUChanging(string value);
    partial void OnMATIEUSUChanged();
    partial void OnMADINHDANHChanging(string value);
    partial void OnMADINHDANHChanged();
    partial void OnTHOIGIANBATDAUChanging(System.DateTime value);
    partial void OnTHOIGIANBATDAUChanged();
    partial void OnTHOIGIANKETTHUCChanging(System.DateTime value);
    partial void OnTHOIGIANKETTHUCChanged();
    partial void OnCHOOChanging(string value);
    partial void OnCHOOChanged();
    partial void OnNGHENGHIEPChanging(string value);
    partial void OnNGHENGHIEPChanged();
    partial void OnNOILAMVIECChanging(string value);
    partial void OnNOILAMVIECChanged();
    #endregion
		
		public TIEUSU()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATIEUSU", DbType="Char(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATIEUSU
		{
			get
			{
				return this._MATIEUSU;
			}
			set
			{
				if ((this._MATIEUSU != value))
				{
					this.OnMATIEUSUChanging(value);
					this.SendPropertyChanging();
					this._MATIEUSU = value;
					this.SendPropertyChanged("MATIEUSU");
					this.OnMATIEUSUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADINHDANH", DbType="Char(12) NOT NULL", CanBeNull=false)]
		public string MADINHDANH
		{
			get
			{
				return this._MADINHDANH;
			}
			set
			{
				if ((this._MADINHDANH != value))
				{
					this.OnMADINHDANHChanging(value);
					this.SendPropertyChanging();
					this._MADINHDANH = value;
					this.SendPropertyChanged("MADINHDANH");
					this.OnMADINHDANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THOIGIANBATDAU", DbType="Date NOT NULL")]
		public System.DateTime THOIGIANBATDAU
		{
			get
			{
				return this._THOIGIANBATDAU;
			}
			set
			{
				if ((this._THOIGIANBATDAU != value))
				{
					this.OnTHOIGIANBATDAUChanging(value);
					this.SendPropertyChanging();
					this._THOIGIANBATDAU = value;
					this.SendPropertyChanged("THOIGIANBATDAU");
					this.OnTHOIGIANBATDAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THOIGIANKETTHUC", DbType="Date NOT NULL")]
		public System.DateTime THOIGIANKETTHUC
		{
			get
			{
				return this._THOIGIANKETTHUC;
			}
			set
			{
				if ((this._THOIGIANKETTHUC != value))
				{
					this.OnTHOIGIANKETTHUCChanging(value);
					this.SendPropertyChanging();
					this._THOIGIANKETTHUC = value;
					this.SendPropertyChanged("THOIGIANKETTHUC");
					this.OnTHOIGIANKETTHUCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHOO", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string CHOO
		{
			get
			{
				return this._CHOO;
			}
			set
			{
				if ((this._CHOO != value))
				{
					this.OnCHOOChanging(value);
					this.SendPropertyChanging();
					this._CHOO = value;
					this.SendPropertyChanged("CHOO");
					this.OnCHOOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGHENGHIEP", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string NGHENGHIEP
		{
			get
			{
				return this._NGHENGHIEP;
			}
			set
			{
				if ((this._NGHENGHIEP != value))
				{
					this.OnNGHENGHIEPChanging(value);
					this.SendPropertyChanging();
					this._NGHENGHIEP = value;
					this.SendPropertyChanged("NGHENGHIEP");
					this.OnNGHENGHIEPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOILAMVIEC", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string NOILAMVIEC
		{
			get
			{
				return this._NOILAMVIEC;
			}
			set
			{
				if ((this._NOILAMVIEC != value))
				{
					this.OnNOILAMVIECChanging(value);
					this.SendPropertyChanging();
					this._NOILAMVIEC = value;
					this.SendPropertyChanged("NOILAMVIEC");
					this.OnNOILAMVIECChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
