#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLHK")]
	public partial class quanlyhokhauDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCANBO(CANBO instance);
    partial void UpdateCANBO(CANBO instance);
    partial void DeleteCANBO(CANBO instance);
    partial void InsertXAPHUONGTHITRAN(XAPHUONGTHITRAN instance);
    partial void UpdateXAPHUONGTHITRAN(XAPHUONGTHITRAN instance);
    partial void DeleteXAPHUONGTHITRAN(XAPHUONGTHITRAN instance);
    partial void InsertHOCSINHSINHVIEN(HOCSINHSINHVIEN instance);
    partial void UpdateHOCSINHSINHVIEN(HOCSINHSINHVIEN instance);
    partial void DeleteHOCSINHSINHVIEN(HOCSINHSINHVIEN instance);
    partial void InsertNHANKHAU(NHANKHAU instance);
    partial void UpdateNHANKHAU(NHANKHAU instance);
    partial void DeleteNHANKHAU(NHANKHAU instance);
    partial void InsertNHANKHAUTAMTRU(NHANKHAUTAMTRU instance);
    partial void UpdateNHANKHAUTAMTRU(NHANKHAUTAMTRU instance);
    partial void DeleteNHANKHAUTAMTRU(NHANKHAUTAMTRU instance);
    partial void InsertNHANKHAUTAMVANG(NHANKHAUTAMVANG instance);
    partial void UpdateNHANKHAUTAMVANG(NHANKHAUTAMVANG instance);
    partial void DeleteNHANKHAUTAMVANG(NHANKHAUTAMVANG instance);
    partial void InsertNHANKHAUTHUONGTRU(NHANKHAUTHUONGTRU instance);
    partial void UpdateNHANKHAUTHUONGTRU(NHANKHAUTHUONGTRU instance);
    partial void DeleteNHANKHAUTHUONGTRU(NHANKHAUTHUONGTRU instance);
    partial void InsertQUANHUYEN(QUANHUYEN instance);
    partial void UpdateQUANHUYEN(QUANHUYEN instance);
    partial void DeleteQUANHUYEN(QUANHUYEN instance);
    partial void InsertSOHOKHAU(SOHOKHAU instance);
    partial void UpdateSOHOKHAU(SOHOKHAU instance);
    partial void DeleteSOHOKHAU(SOHOKHAU instance);
    partial void InsertSOTAMTRU(SOTAMTRU instance);
    partial void UpdateSOTAMTRU(SOTAMTRU instance);
    partial void DeleteSOTAMTRU(SOTAMTRU instance);
    partial void InsertTIENANTIENSU(TIENANTIENSU instance);
    partial void UpdateTIENANTIENSU(TIENANTIENSU instance);
    partial void DeleteTIENANTIENSU(TIENANTIENSU instance);
    partial void InsertTIEUSU(TIEUSU instance);
    partial void UpdateTIEUSU(TIEUSU instance);
    partial void DeleteTIEUSU(TIEUSU instance);
    partial void InsertTINHTHANHPHO(TINHTHANHPHO instance);
    partial void UpdateTINHTHANHPHO(TINHTHANHPHO instance);
    partial void DeleteTINHTHANHPHO(TINHTHANHPHO instance);
    #endregion
		
		public quanlyhokhauDataContext() : 
				base(global::DTO.Properties.Settings.Default.QLHKConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public quanlyhokhauDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public quanlyhokhauDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public quanlyhokhauDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public quanlyhokhauDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CANBO> CANBOs
		{
			get
			{
				return this.GetTable<CANBO>();
			}
		}
		
		public System.Data.Linq.Table<XAPHUONGTHITRAN> XAPHUONGTHITRANs
		{
			get
			{
				return this.GetTable<XAPHUONGTHITRAN>();
			}
		}
		
		public System.Data.Linq.Table<HOCSINHSINHVIEN> HOCSINHSINHVIENs
		{
			get
			{
				return this.GetTable<HOCSINHSINHVIEN>();
			}
		}
		
		public System.Data.Linq.Table<NHANKHAU> NHANKHAUs
		{
			get
			{
				return this.GetTable<NHANKHAU>();
			}
		}
		
		public System.Data.Linq.Table<NHANKHAUTAMTRU> NHANKHAUTAMTRUs
		{
			get
			{
				return this.GetTable<NHANKHAUTAMTRU>();
			}
		}
		
		public System.Data.Linq.Table<NHANKHAUTAMVANG> NHANKHAUTAMVANGs
		{
			get
			{
				return this.GetTable<NHANKHAUTAMVANG>();
			}
		}
		
		public System.Data.Linq.Table<NHANKHAUTHUONGTRU> NHANKHAUTHUONGTRUs
		{
			get
			{
				return this.GetTable<NHANKHAUTHUONGTRU>();
			}
		}
		
		public System.Data.Linq.Table<QUANHUYEN> QUANHUYENs
		{
			get
			{
				return this.GetTable<QUANHUYEN>();
			}
		}
		
		public System.Data.Linq.Table<SOHOKHAU> SOHOKHAUs
		{
			get
			{
				return this.GetTable<SOHOKHAU>();
			}
		}
		
		public System.Data.Linq.Table<SOTAMTRU> SOTAMTRUs
		{
			get
			{
				return this.GetTable<SOTAMTRU>();
			}
		}
		
		public System.Data.Linq.Table<TIENANTIENSU> TIENANTIENSUs
		{
			get
			{
				return this.GetTable<TIENANTIENSU>();
			}
		}
		
		public System.Data.Linq.Table<TIEUSU> TIEUSUs
		{
			get
			{
				return this.GetTable<TIEUSU>();
			}
		}
		
		public System.Data.Linq.Table<TINHTHANHPHO> TINHTHANHPHOs
		{
			get
			{
				return this.GetTable<TINHTHANHPHO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CANBO")]
	public partial class CANBO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MACANBO;
		
		private string _MANHANKHAUTHUONGTRU;
		
		private string _TENTAIKHOAN;
		
		private string _MATKHAU;
		
		private string _LOAICANBO;
		
		private EntityRef<NHANKHAUTHUONGTRU> _NHANKHAUTHUONGTRU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMACANBOChanging(string value);
    partial void OnMACANBOChanged();
    partial void OnMANHANKHAUTHUONGTRUChanging(string value);
    partial void OnMANHANKHAUTHUONGTRUChanged();
    partial void OnTENTAIKHOANChanging(string value);
    partial void OnTENTAIKHOANChanged();
    partial void OnMATKHAUChanging(string value);
    partial void OnMATKHAUChanged();
    partial void OnLOAICANBOChanging(string value);
    partial void OnLOAICANBOChanged();
    #endregion
		
		public CANBO()
		{
			this._NHANKHAUTHUONGTRU = default(EntityRef<NHANKHAUTHUONGTRU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACANBO", DbType="Char(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MACANBO
		{
			get
			{
				return this._MACANBO;
			}
			set
			{
				if ((this._MACANBO != value))
				{
					this.OnMACANBOChanging(value);
					this.SendPropertyChanging();
					this._MACANBO = value;
					this.SendPropertyChanged("MACANBO");
					this.OnMACANBOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANHANKHAUTHUONGTRU", DbType="Char(9)")]
		public string MANHANKHAUTHUONGTRU
		{
			get
			{
				return this._MANHANKHAUTHUONGTRU;
			}
			set
			{
				if ((this._MANHANKHAUTHUONGTRU != value))
				{
					if (this._NHANKHAUTHUONGTRU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANHANKHAUTHUONGTRUChanging(value);
					this.SendPropertyChanging();
					this._MANHANKHAUTHUONGTRU = value;
					this.SendPropertyChanged("MANHANKHAUTHUONGTRU");
					this.OnMANHANKHAUTHUONGTRUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTAIKHOAN", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TENTAIKHOAN
		{
			get
			{
				return this._TENTAIKHOAN;
			}
			set
			{
				if ((this._TENTAIKHOAN != value))
				{
					this.OnTENTAIKHOANChanging(value);
					this.SendPropertyChanging();
					this._TENTAIKHOAN = value;
					this.SendPropertyChanged("TENTAIKHOAN");
					this.OnTENTAIKHOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATKHAU", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string MATKHAU
		{
			get
			{
				return this._MATKHAU;
			}
			set
			{
				if ((this._MATKHAU != value))
				{
					this.OnMATKHAUChanging(value);
					this.SendPropertyChanging();
					this._MATKHAU = value;
					this.SendPropertyChanged("MATKHAU");
					this.OnMATKHAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAICANBO", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string LOAICANBO
		{
			get
			{
				return this._LOAICANBO;
			}
			set
			{
				if ((this._LOAICANBO != value))
				{
					this.OnLOAICANBOChanging(value);
					this.SendPropertyChanging();
					this._LOAICANBO = value;
					this.SendPropertyChanged("LOAICANBO");
					this.OnLOAICANBOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANKHAUTHUONGTRU_CANBO", Storage="_NHANKHAUTHUONGTRU", ThisKey="MANHANKHAUTHUONGTRU", OtherKey="MANHANKHAUTHUONGTRU", IsForeignKey=true)]
		public NHANKHAUTHUONGTRU NHANKHAUTHUONGTRU
		{
			get
			{
				return this._NHANKHAUTHUONGTRU.Entity;
			}
			set
			{
				NHANKHAUTHUONGTRU previousValue = this._NHANKHAUTHUONGTRU.Entity;
				if (((previousValue != value) 
							|| (this._NHANKHAUTHUONGTRU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANKHAUTHUONGTRU.Entity = null;
						previousValue.CANBOs.Remove(this);
					}
					this._NHANKHAUTHUONGTRU.Entity = value;
					if ((value != null))
					{
						value.CANBOs.Add(this);
						this._MANHANKHAUTHUONGTRU = value.MANHANKHAUTHUONGTRU;
					}
					else
					{
						this._MANHANKHAUTHUONGTRU = default(string);
					}
					this.SendPropertyChanged("NHANKHAUTHUONGTRU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.XAPHUONGTHITRAN")]
	public partial class XAPHUONGTHITRAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maxp;
		
		private string _ten;
		
		private string _kieu;
		
		private string _maqh;
		
		private EntityRef<QUANHUYEN> _QUANHUYEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaxpChanging(string value);
    partial void OnmaxpChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void OnkieuChanging(string value);
    partial void OnkieuChanged();
    partial void OnmaqhChanging(string value);
    partial void OnmaqhChanged();
    #endregion
		
		public XAPHUONGTHITRAN()
		{
			this._QUANHUYEN = default(EntityRef<QUANHUYEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maxp", DbType="NVarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maxp
		{
			get
			{
				return this._maxp;
			}
			set
			{
				if ((this._maxp != value))
				{
					this.OnmaxpChanging(value);
					this.SendPropertyChanging();
					this._maxp = value;
					this.SendPropertyChanged("maxp");
					this.OnmaxpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kieu", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string kieu
		{
			get
			{
				return this._kieu;
			}
			set
			{
				if ((this._kieu != value))
				{
					this.OnkieuChanging(value);
					this.SendPropertyChanging();
					this._kieu = value;
					this.SendPropertyChanged("kieu");
					this.OnkieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maqh", DbType="NVarChar(5)")]
		public string maqh
		{
			get
			{
				return this._maqh;
			}
			set
			{
				if ((this._maqh != value))
				{
					if (this._QUANHUYEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaqhChanging(value);
					this.SendPropertyChanging();
					this._maqh = value;
					this.SendPropertyChanged("maqh");
					this.OnmaqhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QUANHUYEN_XAPHUONGTHITRAN", Storage="_QUANHUYEN", ThisKey="maqh", OtherKey="maqh", IsForeignKey=true)]
		public QUANHUYEN QUANHUYEN
		{
			get
			{
				return this._QUANHUYEN.Entity;
			}
			set
			{
				QUANHUYEN previousValue = this._QUANHUYEN.Entity;
				if (((previousValue != value) 
							|| (this._QUANHUYEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QUANHUYEN.Entity = null;
						previousValue.XAPHUONGTHITRANs.Remove(this);
					}
					this._QUANHUYEN.Entity = value;
					if ((value != null))
					{
						value.XAPHUONGTHITRANs.Add(this);
						this._maqh = value.maqh;
					}
					else
					{
						this._maqh = default(string);
					}
					this.SendPropertyChanged("QUANHUYEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOCSINHSINHVIEN")]
	public partial class HOCSINHSINHVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAHSSV;
		
		private string _MADINHDANH;
		
		private string _TRUONG;
		
		private string _DIACHITHUONGTRU;
		
		private System.DateTime _THOIGIANBATDAUTAMTRUTHUONGTRU;
		
		private System.DateTime _THOIGIANKETTHUCTAMTRUTHUONGTRU;
		
		private string _VIPHAM;
		
		private EntityRef<NHANKHAU> _NHANKHAU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAHSSVChanging(string value);
    partial void OnMAHSSVChanged();
    partial void OnMADINHDANHChanging(string value);
    partial void OnMADINHDANHChanged();
    partial void OnTRUONGChanging(string value);
    partial void OnTRUONGChanged();
    partial void OnDIACHITHUONGTRUChanging(string value);
    partial void OnDIACHITHUONGTRUChanged();
    partial void OnTHOIGIANBATDAUTAMTRUTHUONGTRUChanging(System.DateTime value);
    partial void OnTHOIGIANBATDAUTAMTRUTHUONGTRUChanged();
    partial void OnTHOIGIANKETTHUCTAMTRUTHUONGTRUChanging(System.DateTime value);
    partial void OnTHOIGIANKETTHUCTAMTRUTHUONGTRUChanged();
    partial void OnVIPHAMChanging(string value);
    partial void OnVIPHAMChanged();
    #endregion
		
		public HOCSINHSINHVIEN()
		{
			this._NHANKHAU = default(EntityRef<NHANKHAU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHSSV", DbType="Char(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAHSSV
		{
			get
			{
				return this._MAHSSV;
			}
			set
			{
				if ((this._MAHSSV != value))
				{
					this.OnMAHSSVChanging(value);
					this.SendPropertyChanging();
					this._MAHSSV = value;
					this.SendPropertyChanged("MAHSSV");
					this.OnMAHSSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADINHDANH", DbType="Char(12)")]
		public string MADINHDANH
		{
			get
			{
				return this._MADINHDANH;
			}
			set
			{
				if ((this._MADINHDANH != value))
				{
					if (this._NHANKHAU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMADINHDANHChanging(value);
					this.SendPropertyChanging();
					this._MADINHDANH = value;
					this.SendPropertyChanged("MADINHDANH");
					this.OnMADINHDANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRUONG", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TRUONG
		{
			get
			{
				return this._TRUONG;
			}
			set
			{
				if ((this._TRUONG != value))
				{
					this.OnTRUONGChanging(value);
					this.SendPropertyChanging();
					this._TRUONG = value;
					this.SendPropertyChanged("TRUONG");
					this.OnTRUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHITHUONGTRU", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DIACHITHUONGTRU
		{
			get
			{
				return this._DIACHITHUONGTRU;
			}
			set
			{
				if ((this._DIACHITHUONGTRU != value))
				{
					this.OnDIACHITHUONGTRUChanging(value);
					this.SendPropertyChanging();
					this._DIACHITHUONGTRU = value;
					this.SendPropertyChanged("DIACHITHUONGTRU");
					this.OnDIACHITHUONGTRUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THOIGIANBATDAUTAMTRUTHUONGTRU", DbType="SmallDateTime NOT NULL")]
		public System.DateTime THOIGIANBATDAUTAMTRUTHUONGTRU
		{
			get
			{
				return this._THOIGIANBATDAUTAMTRUTHUONGTRU;
			}
			set
			{
				if ((this._THOIGIANBATDAUTAMTRUTHUONGTRU != value))
				{
					this.OnTHOIGIANBATDAUTAMTRUTHUONGTRUChanging(value);
					this.SendPropertyChanging();
					this._THOIGIANBATDAUTAMTRUTHUONGTRU = value;
					this.SendPropertyChanged("THOIGIANBATDAUTAMTRUTHUONGTRU");
					this.OnTHOIGIANBATDAUTAMTRUTHUONGTRUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THOIGIANKETTHUCTAMTRUTHUONGTRU", DbType="SmallDateTime NOT NULL")]
		public System.DateTime THOIGIANKETTHUCTAMTRUTHUONGTRU
		{
			get
			{
				return this._THOIGIANKETTHUCTAMTRUTHUONGTRU;
			}
			set
			{
				if ((this._THOIGIANKETTHUCTAMTRUTHUONGTRU != value))
				{
					this.OnTHOIGIANKETTHUCTAMTRUTHUONGTRUChanging(value);
					this.SendPropertyChanging();
					this._THOIGIANKETTHUCTAMTRUTHUONGTRU = value;
					this.SendPropertyChanged("THOIGIANKETTHUCTAMTRUTHUONGTRU");
					this.OnTHOIGIANKETTHUCTAMTRUTHUONGTRUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VIPHAM", DbType="NVarChar(100)")]
		public string VIPHAM
		{
			get
			{
				return this._VIPHAM;
			}
			set
			{
				if ((this._VIPHAM != value))
				{
					this.OnVIPHAMChanging(value);
					this.SendPropertyChanging();
					this._VIPHAM = value;
					this.SendPropertyChanged("VIPHAM");
					this.OnVIPHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANKHAU_HOCSINHSINHVIEN", Storage="_NHANKHAU", ThisKey="MADINHDANH", OtherKey="MADINHDANH", IsForeignKey=true)]
		public NHANKHAU NHANKHAU
		{
			get
			{
				return this._NHANKHAU.Entity;
			}
			set
			{
				NHANKHAU previousValue = this._NHANKHAU.Entity;
				if (((previousValue != value) 
							|| (this._NHANKHAU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANKHAU.Entity = null;
						previousValue.HOCSINHSINHVIENs.Remove(this);
					}
					this._NHANKHAU.Entity = value;
					if ((value != null))
					{
						value.HOCSINHSINHVIENs.Add(this);
						this._MADINHDANH = value.MADINHDANH;
					}
					else
					{
						this._MADINHDANH = default(string);
					}
					this.SendPropertyChanged("NHANKHAU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANKHAU")]
	public partial class NHANKHAU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MADINHDANH;
		
		private string _HOTEN;
		
		private string _TENKHAC;
		
		private System.DateTime _NGAYSINH;
		
		private string _GIOITINH;
		
		private string _NOISINH;
		
		private string _NGUYENQUAN;
		
		private string _DANTOC;
		
		private string _TONGIAO;
		
		private string _QUOCTICH;
		
		private string _HOCHIEU;
		
		private string _NOITHUONGTRU;
		
		private string _DIACHIHIENNAY;
		
		private string _SDT;
		
		private string _TRINHDOHOCVAN;
		
		private string _TRINHDOCHUYENMON;
		
		private string _BIETTIENGDANTOC;
		
		private string _TRINHDONGOAINGU;
		
		private string _NGHENGHIEP;
		
		private EntitySet<HOCSINHSINHVIEN> _HOCSINHSINHVIENs;
		
		private EntitySet<NHANKHAUTAMTRU> _NHANKHAUTAMTRUs;
		
		private EntitySet<NHANKHAUTAMVANG> _NHANKHAUTAMVANGs;
		
		private EntitySet<NHANKHAUTHUONGTRU> _NHANKHAUTHUONGTRUs;
		
		private EntitySet<TIENANTIENSU> _TIENANTIENSUs;
		
		private EntitySet<TIEUSU> _TIEUSUs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMADINHDANHChanging(string value);
    partial void OnMADINHDANHChanged();
    partial void OnHOTENChanging(string value);
    partial void OnHOTENChanged();
    partial void OnTENKHACChanging(string value);
    partial void OnTENKHACChanged();
    partial void OnNGAYSINHChanging(System.DateTime value);
    partial void OnNGAYSINHChanged();
    partial void OnGIOITINHChanging(string value);
    partial void OnGIOITINHChanged();
    partial void OnNOISINHChanging(string value);
    partial void OnNOISINHChanged();
    partial void OnNGUYENQUANChanging(string value);
    partial void OnNGUYENQUANChanged();
    partial void OnDANTOCChanging(string value);
    partial void OnDANTOCChanged();
    partial void OnTONGIAOChanging(string value);
    partial void OnTONGIAOChanged();
    partial void OnQUOCTICHChanging(string value);
    partial void OnQUOCTICHChanged();
    partial void OnHOCHIEUChanging(string value);
    partial void OnHOCHIEUChanged();
    partial void OnNOITHUONGTRUChanging(string value);
    partial void OnNOITHUONGTRUChanged();
    partial void OnDIACHIHIENNAYChanging(string value);
    partial void OnDIACHIHIENNAYChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnTRINHDOHOCVANChanging(string value);
    partial void OnTRINHDOHOCVANChanged();
    partial void OnTRINHDOCHUYENMONChanging(string value);
    partial void OnTRINHDOCHUYENMONChanged();
    partial void OnBIETTIENGDANTOCChanging(string value);
    partial void OnBIETTIENGDANTOCChanged();
    partial void OnTRINHDONGOAINGUChanging(string value);
    partial void OnTRINHDONGOAINGUChanged();
    partial void OnNGHENGHIEPChanging(string value);
    partial void OnNGHENGHIEPChanged();
    #endregion
		
		public NHANKHAU()
		{
			this._HOCSINHSINHVIENs = new EntitySet<HOCSINHSINHVIEN>(new Action<HOCSINHSINHVIEN>(this.attach_HOCSINHSINHVIENs), new Action<HOCSINHSINHVIEN>(this.detach_HOCSINHSINHVIENs));
			this._NHANKHAUTAMTRUs = new EntitySet<NHANKHAUTAMTRU>(new Action<NHANKHAUTAMTRU>(this.attach_NHANKHAUTAMTRUs), new Action<NHANKHAUTAMTRU>(this.detach_NHANKHAUTAMTRUs));
			this._NHANKHAUTAMVANGs = new EntitySet<NHANKHAUTAMVANG>(new Action<NHANKHAUTAMVANG>(this.attach_NHANKHAUTAMVANGs), new Action<NHANKHAUTAMVANG>(this.detach_NHANKHAUTAMVANGs));
			this._NHANKHAUTHUONGTRUs = new EntitySet<NHANKHAUTHUONGTRU>(new Action<NHANKHAUTHUONGTRU>(this.attach_NHANKHAUTHUONGTRUs), new Action<NHANKHAUTHUONGTRU>(this.detach_NHANKHAUTHUONGTRUs));
			this._TIENANTIENSUs = new EntitySet<TIENANTIENSU>(new Action<TIENANTIENSU>(this.attach_TIENANTIENSUs), new Action<TIENANTIENSU>(this.detach_TIENANTIENSUs));
			this._TIEUSUs = new EntitySet<TIEUSU>(new Action<TIEUSU>(this.attach_TIEUSUs), new Action<TIEUSU>(this.detach_TIEUSUs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADINHDANH", DbType="Char(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MADINHDANH
		{
			get
			{
				return this._MADINHDANH;
			}
			set
			{
				if ((this._MADINHDANH != value))
				{
					this.OnMADINHDANHChanging(value);
					this.SendPropertyChanging();
					this._MADINHDANH = value;
					this.SendPropertyChanged("MADINHDANH");
					this.OnMADINHDANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HOTEN
		{
			get
			{
				return this._HOTEN;
			}
			set
			{
				if ((this._HOTEN != value))
				{
					this.OnHOTENChanging(value);
					this.SendPropertyChanging();
					this._HOTEN = value;
					this.SendPropertyChanged("HOTEN");
					this.OnHOTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENKHAC", DbType="NVarChar(50)")]
		public string TENKHAC
		{
			get
			{
				return this._TENKHAC;
			}
			set
			{
				if ((this._TENKHAC != value))
				{
					this.OnTENKHACChanging(value);
					this.SendPropertyChanging();
					this._TENKHAC = value;
					this.SendPropertyChanged("TENKHAC");
					this.OnTENKHACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="SmallDateTime NOT NULL")]
		public System.DateTime NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOISINH", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NOISINH
		{
			get
			{
				return this._NOISINH;
			}
			set
			{
				if ((this._NOISINH != value))
				{
					this.OnNOISINHChanging(value);
					this.SendPropertyChanging();
					this._NOISINH = value;
					this.SendPropertyChanged("NOISINH");
					this.OnNOISINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGUYENQUAN", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NGUYENQUAN
		{
			get
			{
				return this._NGUYENQUAN;
			}
			set
			{
				if ((this._NGUYENQUAN != value))
				{
					this.OnNGUYENQUANChanging(value);
					this.SendPropertyChanging();
					this._NGUYENQUAN = value;
					this.SendPropertyChanged("NGUYENQUAN");
					this.OnNGUYENQUANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DANTOC", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string DANTOC
		{
			get
			{
				return this._DANTOC;
			}
			set
			{
				if ((this._DANTOC != value))
				{
					this.OnDANTOCChanging(value);
					this.SendPropertyChanging();
					this._DANTOC = value;
					this.SendPropertyChanged("DANTOC");
					this.OnDANTOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGIAO", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string TONGIAO
		{
			get
			{
				return this._TONGIAO;
			}
			set
			{
				if ((this._TONGIAO != value))
				{
					this.OnTONGIAOChanging(value);
					this.SendPropertyChanging();
					this._TONGIAO = value;
					this.SendPropertyChanged("TONGIAO");
					this.OnTONGIAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUOCTICH", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string QUOCTICH
		{
			get
			{
				return this._QUOCTICH;
			}
			set
			{
				if ((this._QUOCTICH != value))
				{
					this.OnQUOCTICHChanging(value);
					this.SendPropertyChanging();
					this._QUOCTICH = value;
					this.SendPropertyChanged("QUOCTICH");
					this.OnQUOCTICHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOCHIEU", DbType="NVarChar(20)")]
		public string HOCHIEU
		{
			get
			{
				return this._HOCHIEU;
			}
			set
			{
				if ((this._HOCHIEU != value))
				{
					this.OnHOCHIEUChanging(value);
					this.SendPropertyChanging();
					this._HOCHIEU = value;
					this.SendPropertyChanged("HOCHIEU");
					this.OnHOCHIEUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOITHUONGTRU", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NOITHUONGTRU
		{
			get
			{
				return this._NOITHUONGTRU;
			}
			set
			{
				if ((this._NOITHUONGTRU != value))
				{
					this.OnNOITHUONGTRUChanging(value);
					this.SendPropertyChanging();
					this._NOITHUONGTRU = value;
					this.SendPropertyChanged("NOITHUONGTRU");
					this.OnNOITHUONGTRUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHIHIENNAY", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DIACHIHIENNAY
		{
			get
			{
				return this._DIACHIHIENNAY;
			}
			set
			{
				if ((this._DIACHIHIENNAY != value))
				{
					this.OnDIACHIHIENNAYChanging(value);
					this.SendPropertyChanging();
					this._DIACHIHIENNAY = value;
					this.SendPropertyChanged("DIACHIHIENNAY");
					this.OnDIACHIHIENNAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Char(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRINHDOHOCVAN", DbType="NVarChar(100)")]
		public string TRINHDOHOCVAN
		{
			get
			{
				return this._TRINHDOHOCVAN;
			}
			set
			{
				if ((this._TRINHDOHOCVAN != value))
				{
					this.OnTRINHDOHOCVANChanging(value);
					this.SendPropertyChanging();
					this._TRINHDOHOCVAN = value;
					this.SendPropertyChanged("TRINHDOHOCVAN");
					this.OnTRINHDOHOCVANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRINHDOCHUYENMON", DbType="NVarChar(100)")]
		public string TRINHDOCHUYENMON
		{
			get
			{
				return this._TRINHDOCHUYENMON;
			}
			set
			{
				if ((this._TRINHDOCHUYENMON != value))
				{
					this.OnTRINHDOCHUYENMONChanging(value);
					this.SendPropertyChanging();
					this._TRINHDOCHUYENMON = value;
					this.SendPropertyChanged("TRINHDOCHUYENMON");
					this.OnTRINHDOCHUYENMONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIETTIENGDANTOC", DbType="NVarChar(100)")]
		public string BIETTIENGDANTOC
		{
			get
			{
				return this._BIETTIENGDANTOC;
			}
			set
			{
				if ((this._BIETTIENGDANTOC != value))
				{
					this.OnBIETTIENGDANTOCChanging(value);
					this.SendPropertyChanging();
					this._BIETTIENGDANTOC = value;
					this.SendPropertyChanged("BIETTIENGDANTOC");
					this.OnBIETTIENGDANTOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRINHDONGOAINGU", DbType="NVarChar(100)")]
		public string TRINHDONGOAINGU
		{
			get
			{
				return this._TRINHDONGOAINGU;
			}
			set
			{
				if ((this._TRINHDONGOAINGU != value))
				{
					this.OnTRINHDONGOAINGUChanging(value);
					this.SendPropertyChanging();
					this._TRINHDONGOAINGU = value;
					this.SendPropertyChanged("TRINHDONGOAINGU");
					this.OnTRINHDONGOAINGUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGHENGHIEP", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NGHENGHIEP
		{
			get
			{
				return this._NGHENGHIEP;
			}
			set
			{
				if ((this._NGHENGHIEP != value))
				{
					this.OnNGHENGHIEPChanging(value);
					this.SendPropertyChanging();
					this._NGHENGHIEP = value;
					this.SendPropertyChanged("NGHENGHIEP");
					this.OnNGHENGHIEPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANKHAU_HOCSINHSINHVIEN", Storage="_HOCSINHSINHVIENs", ThisKey="MADINHDANH", OtherKey="MADINHDANH")]
		public EntitySet<HOCSINHSINHVIEN> HOCSINHSINHVIENs
		{
			get
			{
				return this._HOCSINHSINHVIENs;
			}
			set
			{
				this._HOCSINHSINHVIENs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANKHAU_NHANKHAUTAMTRU", Storage="_NHANKHAUTAMTRUs", ThisKey="MADINHDANH", OtherKey="MADINHDANH")]
		public EntitySet<NHANKHAUTAMTRU> NHANKHAUTAMTRUs
		{
			get
			{
				return this._NHANKHAUTAMTRUs;
			}
			set
			{
				this._NHANKHAUTAMTRUs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANKHAU_NHANKHAUTAMVANG", Storage="_NHANKHAUTAMVANGs", ThisKey="MADINHDANH", OtherKey="MADINHDANH")]
		public EntitySet<NHANKHAUTAMVANG> NHANKHAUTAMVANGs
		{
			get
			{
				return this._NHANKHAUTAMVANGs;
			}
			set
			{
				this._NHANKHAUTAMVANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANKHAU_NHANKHAUTHUONGTRU", Storage="_NHANKHAUTHUONGTRUs", ThisKey="MADINHDANH", OtherKey="MADINHDANH")]
		public EntitySet<NHANKHAUTHUONGTRU> NHANKHAUTHUONGTRUs
		{
			get
			{
				return this._NHANKHAUTHUONGTRUs;
			}
			set
			{
				this._NHANKHAUTHUONGTRUs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANKHAU_TIENANTIENSU", Storage="_TIENANTIENSUs", ThisKey="MADINHDANH", OtherKey="MADINHDANH")]
		public EntitySet<TIENANTIENSU> TIENANTIENSUs
		{
			get
			{
				return this._TIENANTIENSUs;
			}
			set
			{
				this._TIENANTIENSUs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANKHAU_TIEUSU", Storage="_TIEUSUs", ThisKey="MADINHDANH", OtherKey="MADINHDANH")]
		public EntitySet<TIEUSU> TIEUSUs
		{
			get
			{
				return this._TIEUSUs;
			}
			set
			{
				this._TIEUSUs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOCSINHSINHVIENs(HOCSINHSINHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.NHANKHAU = this;
		}
		
		private void detach_HOCSINHSINHVIENs(HOCSINHSINHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.NHANKHAU = null;
		}
		
		private void attach_NHANKHAUTAMTRUs(NHANKHAUTAMTRU entity)
		{
			this.SendPropertyChanging();
			entity.NHANKHAU = this;
		}
		
		private void detach_NHANKHAUTAMTRUs(NHANKHAUTAMTRU entity)
		{
			this.SendPropertyChanging();
			entity.NHANKHAU = null;
		}
		
		private void attach_NHANKHAUTAMVANGs(NHANKHAUTAMVANG entity)
		{
			this.SendPropertyChanging();
			entity.NHANKHAU = this;
		}
		
		private void detach_NHANKHAUTAMVANGs(NHANKHAUTAMVANG entity)
		{
			this.SendPropertyChanging();
			entity.NHANKHAU = null;
		}
		
		private void attach_NHANKHAUTHUONGTRUs(NHANKHAUTHUONGTRU entity)
		{
			this.SendPropertyChanging();
			entity.NHANKHAU = this;
		}
		
		private void detach_NHANKHAUTHUONGTRUs(NHANKHAUTHUONGTRU entity)
		{
			this.SendPropertyChanging();
			entity.NHANKHAU = null;
		}
		
		private void attach_TIENANTIENSUs(TIENANTIENSU entity)
		{
			this.SendPropertyChanging();
			entity.NHANKHAU = this;
		}
		
		private void detach_TIENANTIENSUs(TIENANTIENSU entity)
		{
			this.SendPropertyChanging();
			entity.NHANKHAU = null;
		}
		
		private void attach_TIEUSUs(TIEUSU entity)
		{
			this.SendPropertyChanging();
			entity.NHANKHAU = this;
		}
		
		private void detach_TIEUSUs(TIEUSU entity)
		{
			this.SendPropertyChanging();
			entity.NHANKHAU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANKHAUTAMTRU")]
	public partial class NHANKHAUTAMTRU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANHANKHAUTAMTRU;
		
		private string _MADINHDANH;
		
		private string _SOSOTAMTRU;
		
		private string _NOITAMTRU;
		
		private System.DateTime _TUNGAY;
		
		private System.DateTime _DENNGAY;
		
		private string _LYDO;
		
		private EntityRef<NHANKHAU> _NHANKHAU;
		
		private EntityRef<SOTAMTRU> _SOTAMTRU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANHANKHAUTAMTRUChanging(string value);
    partial void OnMANHANKHAUTAMTRUChanged();
    partial void OnMADINHDANHChanging(string value);
    partial void OnMADINHDANHChanged();
    partial void OnSOSOTAMTRUChanging(string value);
    partial void OnSOSOTAMTRUChanged();
    partial void OnNOITAMTRUChanging(string value);
    partial void OnNOITAMTRUChanged();
    partial void OnTUNGAYChanging(System.DateTime value);
    partial void OnTUNGAYChanged();
    partial void OnDENNGAYChanging(System.DateTime value);
    partial void OnDENNGAYChanged();
    partial void OnLYDOChanging(string value);
    partial void OnLYDOChanged();
    #endregion
		
		public NHANKHAUTAMTRU()
		{
			this._NHANKHAU = default(EntityRef<NHANKHAU>);
			this._SOTAMTRU = default(EntityRef<SOTAMTRU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANHANKHAUTAMTRU", DbType="Char(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANHANKHAUTAMTRU
		{
			get
			{
				return this._MANHANKHAUTAMTRU;
			}
			set
			{
				if ((this._MANHANKHAUTAMTRU != value))
				{
					this.OnMANHANKHAUTAMTRUChanging(value);
					this.SendPropertyChanging();
					this._MANHANKHAUTAMTRU = value;
					this.SendPropertyChanged("MANHANKHAUTAMTRU");
					this.OnMANHANKHAUTAMTRUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADINHDANH", DbType="Char(12)")]
		public string MADINHDANH
		{
			get
			{
				return this._MADINHDANH;
			}
			set
			{
				if ((this._MADINHDANH != value))
				{
					if (this._NHANKHAU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMADINHDANHChanging(value);
					this.SendPropertyChanging();
					this._MADINHDANH = value;
					this.SendPropertyChanged("MADINHDANH");
					this.OnMADINHDANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOSOTAMTRU", DbType="Char(9)")]
		public string SOSOTAMTRU
		{
			get
			{
				return this._SOSOTAMTRU;
			}
			set
			{
				if ((this._SOSOTAMTRU != value))
				{
					if (this._SOTAMTRU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSOSOTAMTRUChanging(value);
					this.SendPropertyChanging();
					this._SOSOTAMTRU = value;
					this.SendPropertyChanged("SOSOTAMTRU");
					this.OnSOSOTAMTRUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOITAMTRU", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NOITAMTRU
		{
			get
			{
				return this._NOITAMTRU;
			}
			set
			{
				if ((this._NOITAMTRU != value))
				{
					this.OnNOITAMTRUChanging(value);
					this.SendPropertyChanging();
					this._NOITAMTRU = value;
					this.SendPropertyChanged("NOITAMTRU");
					this.OnNOITAMTRUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TUNGAY", DbType="SmallDateTime NOT NULL")]
		public System.DateTime TUNGAY
		{
			get
			{
				return this._TUNGAY;
			}
			set
			{
				if ((this._TUNGAY != value))
				{
					this.OnTUNGAYChanging(value);
					this.SendPropertyChanging();
					this._TUNGAY = value;
					this.SendPropertyChanged("TUNGAY");
					this.OnTUNGAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DENNGAY", DbType="SmallDateTime NOT NULL")]
		public System.DateTime DENNGAY
		{
			get
			{
				return this._DENNGAY;
			}
			set
			{
				if ((this._DENNGAY != value))
				{
					this.OnDENNGAYChanging(value);
					this.SendPropertyChanging();
					this._DENNGAY = value;
					this.SendPropertyChanged("DENNGAY");
					this.OnDENNGAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LYDO", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string LYDO
		{
			get
			{
				return this._LYDO;
			}
			set
			{
				if ((this._LYDO != value))
				{
					this.OnLYDOChanging(value);
					this.SendPropertyChanging();
					this._LYDO = value;
					this.SendPropertyChanged("LYDO");
					this.OnLYDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANKHAU_NHANKHAUTAMTRU", Storage="_NHANKHAU", ThisKey="MADINHDANH", OtherKey="MADINHDANH", IsForeignKey=true)]
		public NHANKHAU NHANKHAU
		{
			get
			{
				return this._NHANKHAU.Entity;
			}
			set
			{
				NHANKHAU previousValue = this._NHANKHAU.Entity;
				if (((previousValue != value) 
							|| (this._NHANKHAU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANKHAU.Entity = null;
						previousValue.NHANKHAUTAMTRUs.Remove(this);
					}
					this._NHANKHAU.Entity = value;
					if ((value != null))
					{
						value.NHANKHAUTAMTRUs.Add(this);
						this._MADINHDANH = value.MADINHDANH;
					}
					else
					{
						this._MADINHDANH = default(string);
					}
					this.SendPropertyChanged("NHANKHAU");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SOTAMTRU_NHANKHAUTAMTRU", Storage="_SOTAMTRU", ThisKey="SOSOTAMTRU", OtherKey="SOSOTAMTRU", IsForeignKey=true)]
		public SOTAMTRU SOTAMTRU
		{
			get
			{
				return this._SOTAMTRU.Entity;
			}
			set
			{
				SOTAMTRU previousValue = this._SOTAMTRU.Entity;
				if (((previousValue != value) 
							|| (this._SOTAMTRU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SOTAMTRU.Entity = null;
						previousValue.NHANKHAUTAMTRUs.Remove(this);
					}
					this._SOTAMTRU.Entity = value;
					if ((value != null))
					{
						value.NHANKHAUTAMTRUs.Add(this);
						this._SOSOTAMTRU = value.SOSOTAMTRU;
					}
					else
					{
						this._SOSOTAMTRU = default(string);
					}
					this.SendPropertyChanged("SOTAMTRU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANKHAUTAMVANG")]
	public partial class NHANKHAUTAMVANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANHANKHAUTAMVANG;
		
		private string _MADINHDANH;
		
		private System.DateTime _NGAYBATDAUTAMVANG;
		
		private System.DateTime _NGAYKETTHUCTAMVANG;
		
		private string _LYDO;
		
		private string _NOIDEN;
		
		private EntityRef<NHANKHAU> _NHANKHAU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANHANKHAUTAMVANGChanging(string value);
    partial void OnMANHANKHAUTAMVANGChanged();
    partial void OnMADINHDANHChanging(string value);
    partial void OnMADINHDANHChanged();
    partial void OnNGAYBATDAUTAMVANGChanging(System.DateTime value);
    partial void OnNGAYBATDAUTAMVANGChanged();
    partial void OnNGAYKETTHUCTAMVANGChanging(System.DateTime value);
    partial void OnNGAYKETTHUCTAMVANGChanged();
    partial void OnLYDOChanging(string value);
    partial void OnLYDOChanged();
    partial void OnNOIDENChanging(string value);
    partial void OnNOIDENChanged();
    #endregion
		
		public NHANKHAUTAMVANG()
		{
			this._NHANKHAU = default(EntityRef<NHANKHAU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANHANKHAUTAMVANG", DbType="Char(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANHANKHAUTAMVANG
		{
			get
			{
				return this._MANHANKHAUTAMVANG;
			}
			set
			{
				if ((this._MANHANKHAUTAMVANG != value))
				{
					this.OnMANHANKHAUTAMVANGChanging(value);
					this.SendPropertyChanging();
					this._MANHANKHAUTAMVANG = value;
					this.SendPropertyChanged("MANHANKHAUTAMVANG");
					this.OnMANHANKHAUTAMVANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADINHDANH", DbType="Char(12)")]
		public string MADINHDANH
		{
			get
			{
				return this._MADINHDANH;
			}
			set
			{
				if ((this._MADINHDANH != value))
				{
					if (this._NHANKHAU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMADINHDANHChanging(value);
					this.SendPropertyChanging();
					this._MADINHDANH = value;
					this.SendPropertyChanged("MADINHDANH");
					this.OnMADINHDANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYBATDAUTAMVANG", DbType="SmallDateTime NOT NULL")]
		public System.DateTime NGAYBATDAUTAMVANG
		{
			get
			{
				return this._NGAYBATDAUTAMVANG;
			}
			set
			{
				if ((this._NGAYBATDAUTAMVANG != value))
				{
					this.OnNGAYBATDAUTAMVANGChanging(value);
					this.SendPropertyChanging();
					this._NGAYBATDAUTAMVANG = value;
					this.SendPropertyChanged("NGAYBATDAUTAMVANG");
					this.OnNGAYBATDAUTAMVANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYKETTHUCTAMVANG", DbType="SmallDateTime NOT NULL")]
		public System.DateTime NGAYKETTHUCTAMVANG
		{
			get
			{
				return this._NGAYKETTHUCTAMVANG;
			}
			set
			{
				if ((this._NGAYKETTHUCTAMVANG != value))
				{
					this.OnNGAYKETTHUCTAMVANGChanging(value);
					this.SendPropertyChanging();
					this._NGAYKETTHUCTAMVANG = value;
					this.SendPropertyChanged("NGAYKETTHUCTAMVANG");
					this.OnNGAYKETTHUCTAMVANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LYDO", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string LYDO
		{
			get
			{
				return this._LYDO;
			}
			set
			{
				if ((this._LYDO != value))
				{
					this.OnLYDOChanging(value);
					this.SendPropertyChanging();
					this._LYDO = value;
					this.SendPropertyChanged("LYDO");
					this.OnLYDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOIDEN", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NOIDEN
		{
			get
			{
				return this._NOIDEN;
			}
			set
			{
				if ((this._NOIDEN != value))
				{
					this.OnNOIDENChanging(value);
					this.SendPropertyChanging();
					this._NOIDEN = value;
					this.SendPropertyChanged("NOIDEN");
					this.OnNOIDENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANKHAU_NHANKHAUTAMVANG", Storage="_NHANKHAU", ThisKey="MADINHDANH", OtherKey="MADINHDANH", IsForeignKey=true)]
		public NHANKHAU NHANKHAU
		{
			get
			{
				return this._NHANKHAU.Entity;
			}
			set
			{
				NHANKHAU previousValue = this._NHANKHAU.Entity;
				if (((previousValue != value) 
							|| (this._NHANKHAU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANKHAU.Entity = null;
						previousValue.NHANKHAUTAMVANGs.Remove(this);
					}
					this._NHANKHAU.Entity = value;
					if ((value != null))
					{
						value.NHANKHAUTAMVANGs.Add(this);
						this._MADINHDANH = value.MADINHDANH;
					}
					else
					{
						this._MADINHDANH = default(string);
					}
					this.SendPropertyChanged("NHANKHAU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANKHAUTHUONGTRU")]
	public partial class NHANKHAUTHUONGTRU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANHANKHAUTHUONGTRU;
		
		private string _MADINHDANH;
		
		private string _SOSOHOKHAU;
		
		private string _DIACHITHUONGTRU;
		
		private string _QUANHEVOICHUHO;
		
		private EntitySet<CANBO> _CANBOs;
		
		private EntityRef<NHANKHAU> _NHANKHAU;
		
		private EntityRef<SOHOKHAU> _SOHOKHAU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANHANKHAUTHUONGTRUChanging(string value);
    partial void OnMANHANKHAUTHUONGTRUChanged();
    partial void OnMADINHDANHChanging(string value);
    partial void OnMADINHDANHChanged();
    partial void OnSOSOHOKHAUChanging(string value);
    partial void OnSOSOHOKHAUChanged();
    partial void OnDIACHITHUONGTRUChanging(string value);
    partial void OnDIACHITHUONGTRUChanged();
    partial void OnQUANHEVOICHUHOChanging(string value);
    partial void OnQUANHEVOICHUHOChanged();
    #endregion
		
		public NHANKHAUTHUONGTRU()
		{
			this._CANBOs = new EntitySet<CANBO>(new Action<CANBO>(this.attach_CANBOs), new Action<CANBO>(this.detach_CANBOs));
			this._NHANKHAU = default(EntityRef<NHANKHAU>);
			this._SOHOKHAU = default(EntityRef<SOHOKHAU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANHANKHAUTHUONGTRU", DbType="Char(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANHANKHAUTHUONGTRU
		{
			get
			{
				return this._MANHANKHAUTHUONGTRU;
			}
			set
			{
				if ((this._MANHANKHAUTHUONGTRU != value))
				{
					this.OnMANHANKHAUTHUONGTRUChanging(value);
					this.SendPropertyChanging();
					this._MANHANKHAUTHUONGTRU = value;
					this.SendPropertyChanged("MANHANKHAUTHUONGTRU");
					this.OnMANHANKHAUTHUONGTRUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADINHDANH", DbType="Char(12)")]
		public string MADINHDANH
		{
			get
			{
				return this._MADINHDANH;
			}
			set
			{
				if ((this._MADINHDANH != value))
				{
					if (this._NHANKHAU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMADINHDANHChanging(value);
					this.SendPropertyChanging();
					this._MADINHDANH = value;
					this.SendPropertyChanged("MADINHDANH");
					this.OnMADINHDANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOSOHOKHAU", DbType="Char(9)")]
		public string SOSOHOKHAU
		{
			get
			{
				return this._SOSOHOKHAU;
			}
			set
			{
				if ((this._SOSOHOKHAU != value))
				{
					if (this._SOHOKHAU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSOSOHOKHAUChanging(value);
					this.SendPropertyChanging();
					this._SOSOHOKHAU = value;
					this.SendPropertyChanged("SOSOHOKHAU");
					this.OnSOSOHOKHAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHITHUONGTRU", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DIACHITHUONGTRU
		{
			get
			{
				return this._DIACHITHUONGTRU;
			}
			set
			{
				if ((this._DIACHITHUONGTRU != value))
				{
					this.OnDIACHITHUONGTRUChanging(value);
					this.SendPropertyChanging();
					this._DIACHITHUONGTRU = value;
					this.SendPropertyChanged("DIACHITHUONGTRU");
					this.OnDIACHITHUONGTRUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANHEVOICHUHO", DbType="NVarChar(100)")]
		public string QUANHEVOICHUHO
		{
			get
			{
				return this._QUANHEVOICHUHO;
			}
			set
			{
				if ((this._QUANHEVOICHUHO != value))
				{
					this.OnQUANHEVOICHUHOChanging(value);
					this.SendPropertyChanging();
					this._QUANHEVOICHUHO = value;
					this.SendPropertyChanged("QUANHEVOICHUHO");
					this.OnQUANHEVOICHUHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANKHAUTHUONGTRU_CANBO", Storage="_CANBOs", ThisKey="MANHANKHAUTHUONGTRU", OtherKey="MANHANKHAUTHUONGTRU")]
		public EntitySet<CANBO> CANBOs
		{
			get
			{
				return this._CANBOs;
			}
			set
			{
				this._CANBOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANKHAU_NHANKHAUTHUONGTRU", Storage="_NHANKHAU", ThisKey="MADINHDANH", OtherKey="MADINHDANH", IsForeignKey=true)]
		public NHANKHAU NHANKHAU
		{
			get
			{
				return this._NHANKHAU.Entity;
			}
			set
			{
				NHANKHAU previousValue = this._NHANKHAU.Entity;
				if (((previousValue != value) 
							|| (this._NHANKHAU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANKHAU.Entity = null;
						previousValue.NHANKHAUTHUONGTRUs.Remove(this);
					}
					this._NHANKHAU.Entity = value;
					if ((value != null))
					{
						value.NHANKHAUTHUONGTRUs.Add(this);
						this._MADINHDANH = value.MADINHDANH;
					}
					else
					{
						this._MADINHDANH = default(string);
					}
					this.SendPropertyChanged("NHANKHAU");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SOHOKHAU_NHANKHAUTHUONGTRU", Storage="_SOHOKHAU", ThisKey="SOSOHOKHAU", OtherKey="SOSOHOKHAU", IsForeignKey=true)]
		public SOHOKHAU SOHOKHAU
		{
			get
			{
				return this._SOHOKHAU.Entity;
			}
			set
			{
				SOHOKHAU previousValue = this._SOHOKHAU.Entity;
				if (((previousValue != value) 
							|| (this._SOHOKHAU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SOHOKHAU.Entity = null;
						previousValue.NHANKHAUTHUONGTRUs.Remove(this);
					}
					this._SOHOKHAU.Entity = value;
					if ((value != null))
					{
						value.NHANKHAUTHUONGTRUs.Add(this);
						this._SOSOHOKHAU = value.SOSOHOKHAU;
					}
					else
					{
						this._SOSOHOKHAU = default(string);
					}
					this.SendPropertyChanged("SOHOKHAU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CANBOs(CANBO entity)
		{
			this.SendPropertyChanging();
			entity.NHANKHAUTHUONGTRU = this;
		}
		
		private void detach_CANBOs(CANBO entity)
		{
			this.SendPropertyChanging();
			entity.NHANKHAUTHUONGTRU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QUANHUYEN")]
	public partial class QUANHUYEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maqh;
		
		private string _ten;
		
		private string _kieu;
		
		private string _matp;
		
		private EntitySet<XAPHUONGTHITRAN> _XAPHUONGTHITRANs;
		
		private EntityRef<TINHTHANHPHO> _TINHTHANHPHO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaqhChanging(string value);
    partial void OnmaqhChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void OnkieuChanging(string value);
    partial void OnkieuChanged();
    partial void OnmatpChanging(string value);
    partial void OnmatpChanged();
    #endregion
		
		public QUANHUYEN()
		{
			this._XAPHUONGTHITRANs = new EntitySet<XAPHUONGTHITRAN>(new Action<XAPHUONGTHITRAN>(this.attach_XAPHUONGTHITRANs), new Action<XAPHUONGTHITRAN>(this.detach_XAPHUONGTHITRANs));
			this._TINHTHANHPHO = default(EntityRef<TINHTHANHPHO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maqh", DbType="NVarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maqh
		{
			get
			{
				return this._maqh;
			}
			set
			{
				if ((this._maqh != value))
				{
					this.OnmaqhChanging(value);
					this.SendPropertyChanging();
					this._maqh = value;
					this.SendPropertyChanged("maqh");
					this.OnmaqhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kieu", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string kieu
		{
			get
			{
				return this._kieu;
			}
			set
			{
				if ((this._kieu != value))
				{
					this.OnkieuChanging(value);
					this.SendPropertyChanging();
					this._kieu = value;
					this.SendPropertyChanged("kieu");
					this.OnkieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matp", DbType="NVarChar(5)")]
		public string matp
		{
			get
			{
				return this._matp;
			}
			set
			{
				if ((this._matp != value))
				{
					if (this._TINHTHANHPHO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmatpChanging(value);
					this.SendPropertyChanging();
					this._matp = value;
					this.SendPropertyChanged("matp");
					this.OnmatpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QUANHUYEN_XAPHUONGTHITRAN", Storage="_XAPHUONGTHITRANs", ThisKey="maqh", OtherKey="maqh")]
		public EntitySet<XAPHUONGTHITRAN> XAPHUONGTHITRANs
		{
			get
			{
				return this._XAPHUONGTHITRANs;
			}
			set
			{
				this._XAPHUONGTHITRANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TINHTHANHPHO_QUANHUYEN", Storage="_TINHTHANHPHO", ThisKey="matp", OtherKey="matp", IsForeignKey=true)]
		public TINHTHANHPHO TINHTHANHPHO
		{
			get
			{
				return this._TINHTHANHPHO.Entity;
			}
			set
			{
				TINHTHANHPHO previousValue = this._TINHTHANHPHO.Entity;
				if (((previousValue != value) 
							|| (this._TINHTHANHPHO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TINHTHANHPHO.Entity = null;
						previousValue.QUANHUYENs.Remove(this);
					}
					this._TINHTHANHPHO.Entity = value;
					if ((value != null))
					{
						value.QUANHUYENs.Add(this);
						this._matp = value.matp;
					}
					else
					{
						this._matp = default(string);
					}
					this.SendPropertyChanged("TINHTHANHPHO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_XAPHUONGTHITRANs(XAPHUONGTHITRAN entity)
		{
			this.SendPropertyChanging();
			entity.QUANHUYEN = this;
		}
		
		private void detach_XAPHUONGTHITRANs(XAPHUONGTHITRAN entity)
		{
			this.SendPropertyChanging();
			entity.QUANHUYEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SOHOKHAU")]
	public partial class SOHOKHAU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SOSOHOKHAU;
		
		private string _MACHUHO;
		
		private string _DIACHI;
		
		private System.DateTime _NGAYCAP;
		
		private string _SODANGKY;
		
		private EntitySet<NHANKHAUTHUONGTRU> _NHANKHAUTHUONGTRUs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSOSOHOKHAUChanging(string value);
    partial void OnSOSOHOKHAUChanged();
    partial void OnMACHUHOChanging(string value);
    partial void OnMACHUHOChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnNGAYCAPChanging(System.DateTime value);
    partial void OnNGAYCAPChanged();
    partial void OnSODANGKYChanging(string value);
    partial void OnSODANGKYChanged();
    #endregion
		
		public SOHOKHAU()
		{
			this._NHANKHAUTHUONGTRUs = new EntitySet<NHANKHAUTHUONGTRU>(new Action<NHANKHAUTHUONGTRU>(this.attach_NHANKHAUTHUONGTRUs), new Action<NHANKHAUTHUONGTRU>(this.detach_NHANKHAUTHUONGTRUs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOSOHOKHAU", DbType="Char(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SOSOHOKHAU
		{
			get
			{
				return this._SOSOHOKHAU;
			}
			set
			{
				if ((this._SOSOHOKHAU != value))
				{
					this.OnSOSOHOKHAUChanging(value);
					this.SendPropertyChanging();
					this._SOSOHOKHAU = value;
					this.SendPropertyChanged("SOSOHOKHAU");
					this.OnSOSOHOKHAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACHUHO", DbType="Char(9)")]
		public string MACHUHO
		{
			get
			{
				return this._MACHUHO;
			}
			set
			{
				if ((this._MACHUHO != value))
				{
					this.OnMACHUHOChanging(value);
					this.SendPropertyChanging();
					this._MACHUHO = value;
					this.SendPropertyChanged("MACHUHO");
					this.OnMACHUHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYCAP", DbType="SmallDateTime NOT NULL")]
		public System.DateTime NGAYCAP
		{
			get
			{
				return this._NGAYCAP;
			}
			set
			{
				if ((this._NGAYCAP != value))
				{
					this.OnNGAYCAPChanging(value);
					this.SendPropertyChanging();
					this._NGAYCAP = value;
					this.SendPropertyChanged("NGAYCAP");
					this.OnNGAYCAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SODANGKY", DbType="Char(7) NOT NULL", CanBeNull=false)]
		public string SODANGKY
		{
			get
			{
				return this._SODANGKY;
			}
			set
			{
				if ((this._SODANGKY != value))
				{
					this.OnSODANGKYChanging(value);
					this.SendPropertyChanging();
					this._SODANGKY = value;
					this.SendPropertyChanged("SODANGKY");
					this.OnSODANGKYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SOHOKHAU_NHANKHAUTHUONGTRU", Storage="_NHANKHAUTHUONGTRUs", ThisKey="SOSOHOKHAU", OtherKey="SOSOHOKHAU")]
		public EntitySet<NHANKHAUTHUONGTRU> NHANKHAUTHUONGTRUs
		{
			get
			{
				return this._NHANKHAUTHUONGTRUs;
			}
			set
			{
				this._NHANKHAUTHUONGTRUs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NHANKHAUTHUONGTRUs(NHANKHAUTHUONGTRU entity)
		{
			this.SendPropertyChanging();
			entity.SOHOKHAU = this;
		}
		
		private void detach_NHANKHAUTHUONGTRUs(NHANKHAUTHUONGTRU entity)
		{
			this.SendPropertyChanging();
			entity.SOHOKHAU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SOTAMTRU")]
	public partial class SOTAMTRU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SOSOTAMTRU;
		
		private string _MACHUHO;
		
		private string _NOITAMTRU;
		
		private System.DateTime _NGAYCAP;
		
		private System.DateTime _DENNGAY;
		
		private EntitySet<NHANKHAUTAMTRU> _NHANKHAUTAMTRUs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSOSOTAMTRUChanging(string value);
    partial void OnSOSOTAMTRUChanged();
    partial void OnMACHUHOChanging(string value);
    partial void OnMACHUHOChanged();
    partial void OnNOITAMTRUChanging(string value);
    partial void OnNOITAMTRUChanged();
    partial void OnNGAYCAPChanging(System.DateTime value);
    partial void OnNGAYCAPChanged();
    partial void OnDENNGAYChanging(System.DateTime value);
    partial void OnDENNGAYChanged();
    #endregion
		
		public SOTAMTRU()
		{
			this._NHANKHAUTAMTRUs = new EntitySet<NHANKHAUTAMTRU>(new Action<NHANKHAUTAMTRU>(this.attach_NHANKHAUTAMTRUs), new Action<NHANKHAUTAMTRU>(this.detach_NHANKHAUTAMTRUs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOSOTAMTRU", DbType="Char(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SOSOTAMTRU
		{
			get
			{
				return this._SOSOTAMTRU;
			}
			set
			{
				if ((this._SOSOTAMTRU != value))
				{
					this.OnSOSOTAMTRUChanging(value);
					this.SendPropertyChanging();
					this._SOSOTAMTRU = value;
					this.SendPropertyChanged("SOSOTAMTRU");
					this.OnSOSOTAMTRUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACHUHO", DbType="Char(9)")]
		public string MACHUHO
		{
			get
			{
				return this._MACHUHO;
			}
			set
			{
				if ((this._MACHUHO != value))
				{
					this.OnMACHUHOChanging(value);
					this.SendPropertyChanging();
					this._MACHUHO = value;
					this.SendPropertyChanged("MACHUHO");
					this.OnMACHUHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOITAMTRU", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NOITAMTRU
		{
			get
			{
				return this._NOITAMTRU;
			}
			set
			{
				if ((this._NOITAMTRU != value))
				{
					this.OnNOITAMTRUChanging(value);
					this.SendPropertyChanging();
					this._NOITAMTRU = value;
					this.SendPropertyChanged("NOITAMTRU");
					this.OnNOITAMTRUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYCAP", DbType="SmallDateTime NOT NULL")]
		public System.DateTime NGAYCAP
		{
			get
			{
				return this._NGAYCAP;
			}
			set
			{
				if ((this._NGAYCAP != value))
				{
					this.OnNGAYCAPChanging(value);
					this.SendPropertyChanging();
					this._NGAYCAP = value;
					this.SendPropertyChanged("NGAYCAP");
					this.OnNGAYCAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DENNGAY", DbType="SmallDateTime NOT NULL")]
		public System.DateTime DENNGAY
		{
			get
			{
				return this._DENNGAY;
			}
			set
			{
				if ((this._DENNGAY != value))
				{
					this.OnDENNGAYChanging(value);
					this.SendPropertyChanging();
					this._DENNGAY = value;
					this.SendPropertyChanged("DENNGAY");
					this.OnDENNGAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SOTAMTRU_NHANKHAUTAMTRU", Storage="_NHANKHAUTAMTRUs", ThisKey="SOSOTAMTRU", OtherKey="SOSOTAMTRU")]
		public EntitySet<NHANKHAUTAMTRU> NHANKHAUTAMTRUs
		{
			get
			{
				return this._NHANKHAUTAMTRUs;
			}
			set
			{
				this._NHANKHAUTAMTRUs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NHANKHAUTAMTRUs(NHANKHAUTAMTRU entity)
		{
			this.SendPropertyChanging();
			entity.SOTAMTRU = this;
		}
		
		private void detach_NHANKHAUTAMTRUs(NHANKHAUTAMTRU entity)
		{
			this.SendPropertyChanging();
			entity.SOTAMTRU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TIENANTIENSU")]
	public partial class TIENANTIENSU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATIENANTIENSU;
		
		private string _MADINHDANH;
		
		private string _TOIDANH;
		
		private string _HINHPHAT;
		
		private string _BANAN;
		
		private System.DateTime _NGAYPHAT;
		
		private EntityRef<NHANKHAU> _NHANKHAU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATIENANTIENSUChanging(string value);
    partial void OnMATIENANTIENSUChanged();
    partial void OnMADINHDANHChanging(string value);
    partial void OnMADINHDANHChanged();
    partial void OnTOIDANHChanging(string value);
    partial void OnTOIDANHChanged();
    partial void OnHINHPHATChanging(string value);
    partial void OnHINHPHATChanged();
    partial void OnBANANChanging(string value);
    partial void OnBANANChanged();
    partial void OnNGAYPHATChanging(System.DateTime value);
    partial void OnNGAYPHATChanged();
    #endregion
		
		public TIENANTIENSU()
		{
			this._NHANKHAU = default(EntityRef<NHANKHAU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATIENANTIENSU", DbType="Char(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATIENANTIENSU
		{
			get
			{
				return this._MATIENANTIENSU;
			}
			set
			{
				if ((this._MATIENANTIENSU != value))
				{
					this.OnMATIENANTIENSUChanging(value);
					this.SendPropertyChanging();
					this._MATIENANTIENSU = value;
					this.SendPropertyChanged("MATIENANTIENSU");
					this.OnMATIENANTIENSUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADINHDANH", DbType="Char(12)")]
		public string MADINHDANH
		{
			get
			{
				return this._MADINHDANH;
			}
			set
			{
				if ((this._MADINHDANH != value))
				{
					if (this._NHANKHAU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMADINHDANHChanging(value);
					this.SendPropertyChanging();
					this._MADINHDANH = value;
					this.SendPropertyChanged("MADINHDANH");
					this.OnMADINHDANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOIDANH", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TOIDANH
		{
			get
			{
				return this._TOIDANH;
			}
			set
			{
				if ((this._TOIDANH != value))
				{
					this.OnTOIDANHChanging(value);
					this.SendPropertyChanging();
					this._TOIDANH = value;
					this.SendPropertyChanged("TOIDANH");
					this.OnTOIDANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHPHAT", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string HINHPHAT
		{
			get
			{
				return this._HINHPHAT;
			}
			set
			{
				if ((this._HINHPHAT != value))
				{
					this.OnHINHPHATChanging(value);
					this.SendPropertyChanging();
					this._HINHPHAT = value;
					this.SendPropertyChanged("HINHPHAT");
					this.OnHINHPHATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BANAN", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string BANAN
		{
			get
			{
				return this._BANAN;
			}
			set
			{
				if ((this._BANAN != value))
				{
					this.OnBANANChanging(value);
					this.SendPropertyChanging();
					this._BANAN = value;
					this.SendPropertyChanged("BANAN");
					this.OnBANANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYPHAT", DbType="SmallDateTime NOT NULL")]
		public System.DateTime NGAYPHAT
		{
			get
			{
				return this._NGAYPHAT;
			}
			set
			{
				if ((this._NGAYPHAT != value))
				{
					this.OnNGAYPHATChanging(value);
					this.SendPropertyChanging();
					this._NGAYPHAT = value;
					this.SendPropertyChanged("NGAYPHAT");
					this.OnNGAYPHATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANKHAU_TIENANTIENSU", Storage="_NHANKHAU", ThisKey="MADINHDANH", OtherKey="MADINHDANH", IsForeignKey=true)]
		public NHANKHAU NHANKHAU
		{
			get
			{
				return this._NHANKHAU.Entity;
			}
			set
			{
				NHANKHAU previousValue = this._NHANKHAU.Entity;
				if (((previousValue != value) 
							|| (this._NHANKHAU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANKHAU.Entity = null;
						previousValue.TIENANTIENSUs.Remove(this);
					}
					this._NHANKHAU.Entity = value;
					if ((value != null))
					{
						value.TIENANTIENSUs.Add(this);
						this._MADINHDANH = value.MADINHDANH;
					}
					else
					{
						this._MADINHDANH = default(string);
					}
					this.SendPropertyChanged("NHANKHAU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TIEUSU")]
	public partial class TIEUSU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATIEUSU;
		
		private string _MADINHDANH;
		
		private System.DateTime _THOIGIANBATDAU;
		
		private System.DateTime _THOIGIANKETTHUC;
		
		private string _CHOO;
		
		private string _NGHENGHIEP;
		
		private string _NOILAMVIEC;
		
		private EntityRef<NHANKHAU> _NHANKHAU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATIEUSUChanging(string value);
    partial void OnMATIEUSUChanged();
    partial void OnMADINHDANHChanging(string value);
    partial void OnMADINHDANHChanged();
    partial void OnTHOIGIANBATDAUChanging(System.DateTime value);
    partial void OnTHOIGIANBATDAUChanged();
    partial void OnTHOIGIANKETTHUCChanging(System.DateTime value);
    partial void OnTHOIGIANKETTHUCChanged();
    partial void OnCHOOChanging(string value);
    partial void OnCHOOChanged();
    partial void OnNGHENGHIEPChanging(string value);
    partial void OnNGHENGHIEPChanged();
    partial void OnNOILAMVIECChanging(string value);
    partial void OnNOILAMVIECChanged();
    #endregion
		
		public TIEUSU()
		{
			this._NHANKHAU = default(EntityRef<NHANKHAU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATIEUSU", DbType="Char(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATIEUSU
		{
			get
			{
				return this._MATIEUSU;
			}
			set
			{
				if ((this._MATIEUSU != value))
				{
					this.OnMATIEUSUChanging(value);
					this.SendPropertyChanging();
					this._MATIEUSU = value;
					this.SendPropertyChanged("MATIEUSU");
					this.OnMATIEUSUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADINHDANH", DbType="Char(12)")]
		public string MADINHDANH
		{
			get
			{
				return this._MADINHDANH;
			}
			set
			{
				if ((this._MADINHDANH != value))
				{
					if (this._NHANKHAU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMADINHDANHChanging(value);
					this.SendPropertyChanging();
					this._MADINHDANH = value;
					this.SendPropertyChanged("MADINHDANH");
					this.OnMADINHDANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THOIGIANBATDAU", DbType="SmallDateTime NOT NULL")]
		public System.DateTime THOIGIANBATDAU
		{
			get
			{
				return this._THOIGIANBATDAU;
			}
			set
			{
				if ((this._THOIGIANBATDAU != value))
				{
					this.OnTHOIGIANBATDAUChanging(value);
					this.SendPropertyChanging();
					this._THOIGIANBATDAU = value;
					this.SendPropertyChanged("THOIGIANBATDAU");
					this.OnTHOIGIANBATDAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THOIGIANKETTHUC", DbType="SmallDateTime NOT NULL")]
		public System.DateTime THOIGIANKETTHUC
		{
			get
			{
				return this._THOIGIANKETTHUC;
			}
			set
			{
				if ((this._THOIGIANKETTHUC != value))
				{
					this.OnTHOIGIANKETTHUCChanging(value);
					this.SendPropertyChanging();
					this._THOIGIANKETTHUC = value;
					this.SendPropertyChanged("THOIGIANKETTHUC");
					this.OnTHOIGIANKETTHUCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHOO", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string CHOO
		{
			get
			{
				return this._CHOO;
			}
			set
			{
				if ((this._CHOO != value))
				{
					this.OnCHOOChanging(value);
					this.SendPropertyChanging();
					this._CHOO = value;
					this.SendPropertyChanged("CHOO");
					this.OnCHOOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGHENGHIEP", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NGHENGHIEP
		{
			get
			{
				return this._NGHENGHIEP;
			}
			set
			{
				if ((this._NGHENGHIEP != value))
				{
					this.OnNGHENGHIEPChanging(value);
					this.SendPropertyChanging();
					this._NGHENGHIEP = value;
					this.SendPropertyChanged("NGHENGHIEP");
					this.OnNGHENGHIEPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOILAMVIEC", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NOILAMVIEC
		{
			get
			{
				return this._NOILAMVIEC;
			}
			set
			{
				if ((this._NOILAMVIEC != value))
				{
					this.OnNOILAMVIECChanging(value);
					this.SendPropertyChanging();
					this._NOILAMVIEC = value;
					this.SendPropertyChanged("NOILAMVIEC");
					this.OnNOILAMVIECChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANKHAU_TIEUSU", Storage="_NHANKHAU", ThisKey="MADINHDANH", OtherKey="MADINHDANH", IsForeignKey=true)]
		public NHANKHAU NHANKHAU
		{
			get
			{
				return this._NHANKHAU.Entity;
			}
			set
			{
				NHANKHAU previousValue = this._NHANKHAU.Entity;
				if (((previousValue != value) 
							|| (this._NHANKHAU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANKHAU.Entity = null;
						previousValue.TIEUSUs.Remove(this);
					}
					this._NHANKHAU.Entity = value;
					if ((value != null))
					{
						value.TIEUSUs.Add(this);
						this._MADINHDANH = value.MADINHDANH;
					}
					else
					{
						this._MADINHDANH = default(string);
					}
					this.SendPropertyChanged("NHANKHAU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TINHTHANHPHO")]
	public partial class TINHTHANHPHO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _matp;
		
		private string _ten;
		
		private string _kieu;
		
		private EntitySet<QUANHUYEN> _QUANHUYENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmatpChanging(string value);
    partial void OnmatpChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void OnkieuChanging(string value);
    partial void OnkieuChanged();
    #endregion
		
		public TINHTHANHPHO()
		{
			this._QUANHUYENs = new EntitySet<QUANHUYEN>(new Action<QUANHUYEN>(this.attach_QUANHUYENs), new Action<QUANHUYEN>(this.detach_QUANHUYENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matp", DbType="NVarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string matp
		{
			get
			{
				return this._matp;
			}
			set
			{
				if ((this._matp != value))
				{
					this.OnmatpChanging(value);
					this.SendPropertyChanging();
					this._matp = value;
					this.SendPropertyChanged("matp");
					this.OnmatpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kieu", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string kieu
		{
			get
			{
				return this._kieu;
			}
			set
			{
				if ((this._kieu != value))
				{
					this.OnkieuChanging(value);
					this.SendPropertyChanging();
					this._kieu = value;
					this.SendPropertyChanged("kieu");
					this.OnkieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TINHTHANHPHO_QUANHUYEN", Storage="_QUANHUYENs", ThisKey="matp", OtherKey="matp")]
		public EntitySet<QUANHUYEN> QUANHUYENs
		{
			get
			{
				return this._QUANHUYENs;
			}
			set
			{
				this._QUANHUYENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QUANHUYENs(QUANHUYEN entity)
		{
			this.SendPropertyChanging();
			entity.TINHTHANHPHO = this;
		}
		
		private void detach_QUANHUYENs(QUANHUYEN entity)
		{
			this.SendPropertyChanging();
			entity.TINHTHANHPHO = null;
		}
	}
}
#pragma warning restore 1591
