//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjLinqEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocSinh
    {
        public string MaSo { get; set; }
        public string Ten { get; set; }
        public Nullable<int> NamSinh { get; set; }
        public string MaLop { get; set; }
    }
}
