//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANKHAU
    {
        public string MADINHDANH { get; set; }
        public string HOTEN { get; set; }
        public string TENKHAC { get; set; }
        public System.DateTime NGAYSINH { get; set; }
        public string GIOITINH { get; set; }
        public string NOISINH { get; set; }
        public string NGUYENQUAN { get; set; }
        public string DANTOC { get; set; }
        public string TONGIAO { get; set; }
        public string QUOCTICH { get; set; }
        public string HOCHIEU { get; set; }
        public string NOITHUONGTRU { get; set; }
        public string DIACHIHIENNAY { get; set; }
        public string SDT { get; set; }
        public string TRINHDOHOCVAN { get; set; }
        public string TRINHDOCHUYENMON { get; set; }
        public string BIETTIENGDANTOC { get; set; }
        public string TRINHDONGOAINGU { get; set; }
        public string NGHENGHIEP { get; set; }
    }
}
