//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANKHAUTHUONGTRU
    {
        public string MANHANKHAUTHUONGTRU { get; set; }
        public string MADINHDANH { get; set; }
        public string DIACHITHUONGTRU { get; set; }
        public string QUANHEVOICHUHO { get; set; }
        public string SOSOHOKHAU { get; set; }
    }
}
