//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOHOKHAU
    {
        public string SOSOHOKHAU { get; set; }
        public string MACHUHO { get; set; }
        public string DIACHI { get; set; }
        public System.DateTime NGAYCAP { get; set; }
        public string SODANGKY { get; set; }
    }
}
