//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIENANTIENSU
    {
        public string MATIENANTIENSU { get; set; }
        public string MADINHDANH { get; set; }
        public string TOIDANH { get; set; }
        public string HINHPHAT { get; set; }
        public string BANAN { get; set; }
        public System.DateTime NGAYPHAT { get; set; }
    }
}
