//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TINHTHANHPHO
    {
        public string matp { get; set; }
        public string ten { get; set; }
        public string kieu { get; set; }
    }
}
