//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANBO
    {
        public string MACANBO { get; set; }
        public string MANHANKHAUTHUONGTRU { get; set; }
        public string TENTAIKHOAN { get; set; }
        public string MATKHAU { get; set; }
        public string LOAICANBO { get; set; }
    
        public virtual NHANKHAUTHUONGTRU NHANKHAUTHUONGTRU { get; set; }
    }
}
