//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOHOKHAU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOHOKHAU()
        {
            this.NHANKHAUTHUONGTRUs = new HashSet<NHANKHAUTHUONGTRU>();
        }
    
        public string SOSOHOKHAU { get; set; }
        public string MACHUHO { get; set; }
        public string DIACHI { get; set; }
        public System.DateTime NGAYCAP { get; set; }
        public string SODANGKY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHANKHAUTHUONGTRU> NHANKHAUTHUONGTRUs { get; set; }
    }
}
