//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOTAMTRU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOTAMTRU()
        {
            this.NHANKHAUTAMTRUs = new HashSet<NHANKHAUTAMTRU>();
        }
    
        public string SOSOTAMTRU { get; set; }
        public string MACHUHO { get; set; }
        public string NOITAMTRU { get; set; }
        public System.DateTime NGAYCAP { get; set; }
        public System.DateTime DENNGAY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHANKHAUTAMTRU> NHANKHAUTAMTRUs { get; set; }
    }
}
