//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIEUSU
    {
        public string MATIEUSU { get; set; }
        public string MADINHDANH { get; set; }
        public System.DateTime THOIGIANBATDAU { get; set; }
        public System.DateTime THOIGIANKETTHUC { get; set; }
        public string CHOO { get; set; }
        public string NGHENGHIEP { get; set; }
        public string NOILAMVIEC { get; set; }
    
        public virtual NHANKHAU NHANKHAU { get; set; }
    }
}
